"""Manager-owned task planning helpers."""

from .agent_error_handler import (
    SERVER_ERROR_AGENT_REQUEST_CONTRACT,
    AGENT_ERROR_DIAGNOSIS_CONTRACT,
    SERVER_ERROR_CATALOG_ENTRY_CONTRACT,
    build_server_error_agent_request,
    handle_server_error,
    validate_agent_error_diagnosis,
    validate_server_error_catalog_entry,
    validate_server_error_agent_request,
)
from .control_plane import (
    CompletionReceiptRows,
    TASK_PRIORITY_RANKS,
    TASK_SUMMARY_ORDER_BY,
    fetch_input_bindings,
    fetch_manager_requests,
    fetch_task_summary,
    normalize_completion_receipt,
    persist_input_bindings,
    validate_manager_request,
)
from .dataset_evidence import (
    DatasetEvidenceCollection,
    DatasetEvidenceLayerSummary,
    DatasetEvidenceRoleSummary,
    collect_dataset_evidence_from_database,
    collect_dataset_evidence_from_rows,
)
from .dashboard_read_models import (
    HISTORICAL_TASK_PROGRESS_CONTRACT,
    build_historical_task_progress_summary,
)
from .dataset_expansion import (
    DatasetExpansionDecision,
    DatasetExpansionPlan,
    DatasetRoleEvidence,
    LayerDatasetEvidence,
    build_dataset_expansion_plan,
    decide_dataset_expansion,
)
from .monthly_backfill import (
    DEFAULT_SOURCES,
    MonthlyWindow,
    SourceAvailability,
    iter_monthly_windows,
    plan_monthly_backfill_requests,
)
from .model_promotion import (
    MODEL_PROMOTION_TARGETS,
    REQUEST_KIND as MODEL_PROMOTION_REVIEW_REQUEST_KIND,
    ModelPromotionTarget,
    build_model_promotion_review_request,
    build_model_promotion_review_requests,
)
from .request_payloads import (
    PARAMETER_SCHEMA_REF,
    build_request_task_payload,
    materialize_request_payload,
    materialize_request_payloads,
)
from .request_handoff import (
    RequestHandoffValidation,
    validate_request_handoff,
    validate_request_handoffs,
)
from .review_decision import (
    build_activation_record,
    build_agent_model_promotion_decision,
    build_review_decision,
    validate_activation_record,
    validate_agent_model_promotion_decision,
    validate_review_decision,
)
from .scheduler import (
    ResourceSnapshot,
    SchedulerConfig,
    SchedulerDecision,
    is_regular_us_equity_trading_day,
    market_hours_gate,
    resource_gate,
    run_scheduler_once,
)
from .scheduler_status import HistoricalSchedulerStatus, collect_historical_scheduler_status
from .task_rehearsal import (
    build_rehearsal_receipt,
    build_rehearsal_task_summary,
    persist_rehearsal,
    rehearse_monthly_backfill_task_system,
)

__all__ = [
    "AGENT_ERROR_DIAGNOSIS_CONTRACT",
    "SERVER_ERROR_AGENT_REQUEST_CONTRACT",
    "SERVER_ERROR_CATALOG_ENTRY_CONTRACT",
    "CompletionReceiptRows",
    "DEFAULT_SOURCES",
    "DatasetEvidenceCollection",
    "DatasetEvidenceLayerSummary",
    "DatasetEvidenceRoleSummary",
    "DatasetExpansionDecision",
    "DatasetExpansionPlan",
    "DatasetRoleEvidence",
    "LayerDatasetEvidence",
    "HISTORICAL_TASK_PROGRESS_CONTRACT",
    "HistoricalSchedulerStatus",
    "TASK_PRIORITY_RANKS",
    "TASK_SUMMARY_ORDER_BY",
    "MODEL_PROMOTION_REVIEW_REQUEST_KIND",
    "MODEL_PROMOTION_TARGETS",
    "MonthlyWindow",
    "ModelPromotionTarget",
    "SourceAvailability",
    "build_dataset_expansion_plan",
    "build_historical_task_progress_summary",
    "build_model_promotion_review_request",
    "collect_historical_scheduler_status",
    "collect_dataset_evidence_from_database",
    "collect_dataset_evidence_from_rows",
    "build_activation_record",
    "build_agent_model_promotion_decision",
    "build_model_promotion_review_requests",
    "build_rehearsal_receipt",
    "build_review_decision",
    "validate_server_error_agent_request",
    "validate_agent_error_diagnosis",
    "validate_server_error_catalog_entry",
    "handle_server_error",
    "build_server_error_agent_request",
    "build_rehearsal_task_summary",
    "PARAMETER_SCHEMA_REF",
    "build_request_task_payload",
    "fetch_input_bindings",
    "fetch_manager_requests",
    "fetch_task_summary",
    "decide_dataset_expansion",
    "iter_monthly_windows",
    "materialize_request_payload",
    "materialize_request_payloads",
    "normalize_completion_receipt",
    "persist_input_bindings",
    "persist_rehearsal",
    "plan_monthly_backfill_requests",
    "rehearse_monthly_backfill_task_system",
    "ResourceSnapshot",
    "RequestHandoffValidation",
    "SchedulerConfig",
    "SchedulerDecision",
    "run_scheduler_once",
    "validate_activation_record",
    "validate_agent_model_promotion_decision",
    "is_regular_us_equity_trading_day",
    "market_hours_gate",
    "resource_gate",
    "validate_manager_request",
    "validate_request_handoff",
    "validate_request_handoffs",
    "validate_review_decision",
]
