-- Bootstrap the active trading registry with the currently approved items.
-- Target engine: PostgreSQL.

INSERT INTO trading_registry (id, kind, key, payload_format, payload, path, applies_to, note)
VALUES
  ('aco_Q1M7D4LP', 'acceptance_outcome', 'ACCEPTANCE_OUTCOME_ACCEPTED', 'text', 'accepted', NULL, NULL, 'default shared acceptance outcome value for accepted work'),
  ('aco_H7Y4P1ZD', 'acceptance_outcome', 'ACCEPTANCE_OUTCOME_BLOCKED', 'text', 'blocked', NULL, NULL, 'default shared acceptance outcome value for work blocked from a final decision'),
  ('aco_B8T3W6FN', 'acceptance_outcome', 'ACCEPTANCE_OUTCOME_REJECTED', 'text', 'rejected', NULL, NULL, 'default shared acceptance outcome value for rejected work'),
  ('aco_N5K2R9VC', 'acceptance_outcome', 'ACCEPTANCE_OUTCOME_RETURNED', 'text', 'returned', NULL, NULL, 'default shared acceptance outcome value for work returned for more changes'),
  ('cfg_J7D1K5RP', 'config', 'DEFAULT_TIMEZONE', 'text', 'America/New_York', NULL, NULL, 'default shared timezone for this server'),
  ('cfg_U8C2D6YA', 'config', 'OPENCLAW_DATABASE_URL_SECRET_ALIAS', 'text', 'openclaw/database-url', NULL, NULL, 'approved config key for the active OpenClaw PostgreSQL database URL secret alias; the registry stores the alias reference, not connection secret material'),
  ('dcs_H2W7M4QL', 'docs_status', 'DOCS_STATUS_ALIGNED', 'text', 'aligned', NULL, NULL, 'default shared docs status value when docs match current project reality'),
  ('dcs_X9K5F1VC', 'docs_status', 'DOCS_STATUS_BLOCKED', 'text', 'blocked', NULL, NULL, 'default shared docs status value when docs status cannot be resolved because maintenance is blocked'),
  ('dcs_R6P3T8NA', 'docs_status', 'DOCS_STATUS_DRIFTED', 'text', 'drifted', NULL, NULL, 'default shared docs status value when docs have drifted from current project reality'),
  ('fld_GI3OL5K5', 'field', 'ACCEPTANCE_OUTCOME', 'text', 'acceptance_outcome', NULL, 'acceptance_receipt_slots', 'canonical shared field name for acceptance outcome slots'),
  ('fld_J6FURQOE', 'field', 'ACCEPTANCE_REFERENCE', 'text', 'acceptance_reference', NULL, 'execution_key_slots;acceptance_receipt_slots', 'canonical shared field name for acceptance reference slots'),
  ('fld_XYGQ3TIC', 'field', 'ACCEPTANCE_SUMMARY', 'text', 'acceptance_summary', NULL, 'acceptance_receipt_slots', 'canonical shared field name for acceptance summary slots'),
  ('fld_YLTWJKTJ', 'field', 'ALLOWED_PATHS', 'text', 'allowed_paths', NULL, 'execution_key_slots', 'canonical shared field name for allowed path slots'),
  ('fld_H2OBUVA0', 'field', 'BLOCKED_PATHS', 'text', 'blocked_paths', NULL, 'execution_key_slots', 'canonical shared field name for blocked path slots'),
  ('fld_FN9DUG5U', 'field', 'BLOCKED_TASK_LIST', 'text', 'blocked_task_list', NULL, 'maintenance_output_slots', 'canonical shared field name for blocked task list slots'),
  ('fld_9BAEN7ZS', 'field', 'CHANGED_FILES', 'text', 'changed_files', NULL, 'completion_receipt_slots', 'canonical shared field name for changed file list slots'),
  ('fld_GNNVKXOG', 'field', 'CHANGE_SUMMARY', 'text', 'change_summary', NULL, 'completion_receipt_slots', 'canonical shared field name for change summary slots'),
  ('fld_B29IDITT', 'field', 'CHECK_TIME', 'text', 'check_time', NULL, 'maintenance_output_slots', 'canonical shared field name for maintenance check time slots'),
  ('fld_EIWWF5B5', 'field', 'COMMAND_LIST', 'text', 'command_list', NULL, 'completion_receipt_slots', 'canonical shared field name for command list slots'),
  ('fld_H6WM9AVU', 'field', 'COMPLETION_RECEIPT_REFERENCE', 'text', 'completion_receipt_reference', NULL, 'execution_key_slots', 'canonical shared field name for completion receipt reference slots'),
  ('fld_5NFMUN7N', 'field', 'CONSTRAINTS', 'text', 'constraints', NULL, 'execution_key_slots', 'canonical shared field name for execution constraint slots'),
  ('fld_F4OFEVFJ', 'field', 'DECISION_REFERENCES', 'text', 'decision_references', NULL, 'execution_key_slots;acceptance_receipt_slots', 'canonical shared field name for decision reference slots'),
  ('fld_4UWS48ZI', 'field', 'DICTIONARY_ISSUE_LIST', 'text', 'dictionary_issue_list', NULL, 'maintenance_output_slots', 'canonical shared field name for dictionary issue list slots'),
  ('fld_2EZ9JU7F', 'field', 'DOCS_STATUS', 'text', 'docs_status', NULL, 'maintenance_output_slots', 'canonical shared field name for docs status slots'),
  ('fld_RSIXOXTB', 'field', 'EXPECTED_OUTPUT', 'text', 'expected_output', NULL, 'execution_key_slots', 'canonical shared field name for expected output slots'),
  ('fld_4ZRFN5AJ', 'field', 'FOLLOW_UP_TASK_LIST', 'text', 'follow_up_task_list', NULL, 'maintenance_output_slots', 'canonical shared field name for follow-up task list slots'),
  ('fld_GXYBK246', 'field', 'ISSUE_LIST', 'text', 'issue_list', NULL, 'completion_receipt_slots;acceptance_receipt_slots', 'canonical shared field name for issue list slots'),
  ('fld_BME8UR38', 'field', 'MAINTENANCE_STATUS', 'text', 'maintenance_status', NULL, 'maintenance_output_slots', 'canonical shared field name for maintenance status slots'),
  ('fld_37IEP8QF', 'field', 'MAINTENANCE_SUMMARY', 'text', 'maintenance_summary', NULL, 'maintenance_output_slots', 'canonical shared field name for maintenance summary slots'),
  ('fld_4BVOLV5F', 'field', 'MEMORY_ROUTE_ISSUE_LIST', 'text', 'memory_route_issue_list', NULL, 'maintenance_output_slots', 'canonical shared field name for memory route issue list slots'),
  ('fld_BJGL5P8K', 'field', 'NEXT_TASK_REFERENCE', 'text', 'next_task_reference', NULL, 'acceptance_receipt_slots', 'canonical shared field name for next task reference slots'),
  ('fld_Z7TPA496', 'field', 'OUTPUT_REFERENCE', 'text', 'output_reference', NULL, 'execution_key_slots;completion_receipt_slots', 'canonical shared field name for output reference slots'),
  ('fld_WNQIX52F', 'field', 'PENDING_ACCEPTANCE_LIST', 'text', 'pending_acceptance_list', NULL, 'maintenance_output_slots', 'canonical shared field name for pending acceptance list slots'),
  ('fld_O9Y3PMML', 'field', 'PENDING_DISPATCH_LIST', 'text', 'pending_dispatch_list', NULL, 'maintenance_output_slots', 'canonical shared field name for pending dispatch list slots'),
  ('fld_K8P3M6QA', 'field', 'REGISTRY_ITEM_APPLIES_TO', 'text', 'applies_to', NULL, 'trading_registry', 'canonical column name for trading_registry.applies_to'),
  ('fld_P8L2C4TY', 'field', 'REGISTRY_ITEM_CREATED_AT', 'text', 'created_at', NULL, 'trading_registry', 'canonical column name for trading_registry.created_at'),
  ('fld_A7K3P2Q9', 'field', 'REGISTRY_ITEM_ID', 'text', 'id', NULL, 'trading_registry', 'canonical column name for trading_registry.id'),
  ('fld_R7P1C6LW', 'field', 'REGISTRY_ITEM_KEY', 'text', 'key', NULL, 'trading_registry', 'canonical column name for trading_registry.key'),
  ('fld_M4N8X2KD', 'field', 'REGISTRY_ITEM_KIND', 'text', 'kind', NULL, 'trading_registry', 'canonical column name for trading_registry.kind'),
  ('fld_D3W7K1RM', 'field', 'REGISTRY_ITEM_NOTE', 'text', 'note', NULL, 'trading_registry', 'canonical column name for trading_registry.note'),
  ('fld_M7Q2P8TZ', 'field', 'REGISTRY_ITEM_PATH', 'text', 'path', NULL, 'trading_registry', 'canonical column name for trading_registry.path'),
  ('fld_B6J4N8XP', 'field', 'REGISTRY_ITEM_PAYLOAD', 'text', 'payload', NULL, 'trading_registry', 'canonical column name for trading_registry.payload'),
  ('fld_T9V2H5QS', 'field', 'REGISTRY_ITEM_PAYLOAD_FORMAT', 'text', 'payload_format', NULL, 'trading_registry', 'canonical column name for trading_registry.payload_format'),
  ('fld_Q5F9M2NZ', 'field', 'REGISTRY_ITEM_UPDATED_AT', 'text', 'updated_at', NULL, 'trading_registry', 'canonical column name for trading_registry.updated_at'),
  ('fld_4YALJN0B', 'field', 'REPOSITORY_PATH', 'text', 'repository_path', NULL, 'execution_key_slots;maintenance_output_slots', 'canonical shared field name for repository path slots'),
  ('fld_6XFD3B1C', 'field', 'REVIEWED_COMMANDS', 'text', 'reviewed_commands', NULL, 'acceptance_receipt_slots', 'canonical shared field name for reviewed command list slots'),
  ('fld_Q9KQLPH4', 'field', 'REVIEWED_FILES', 'text', 'reviewed_files', NULL, 'acceptance_receipt_slots', 'canonical shared field name for reviewed file list slots'),
  ('fld_6RJNNWV1', 'field', 'REVIEW_READINESS', 'text', 'review_readiness', NULL, 'completion_receipt_slots', 'canonical shared field name for review readiness slots'),
  ('fld_SBU4RCHA', 'field', 'SPLIT_ISSUE_LIST', 'text', 'split_issue_list', NULL, 'maintenance_output_slots', 'canonical shared field name for split issue list slots'),
  ('fld_PVUM9JE5', 'field', 'TASK_GOAL', 'text', 'task_goal', NULL, 'execution_key_slots', 'canonical shared field name for task goal slots'),
  ('fld_7X5H7N6Y', 'field', 'TASK_IDENTITY', 'text', 'task_identity', NULL, 'task_register_slots;execution_key_slots;completion_receipt_slots;acceptance_receipt_slots', 'canonical shared field name for task identity slots'),
  ('fld_5DVSJFM0', 'field', 'TASK_LIFECYCLE_STATE', 'text', 'task_lifecycle_state', NULL, 'task_register_slots;completion_receipt_slots', 'canonical shared field name for task lifecycle state slots'),
  ('fld_RSO93XMM', 'field', 'TASK_SCOPE', 'text', 'task_scope', NULL, 'execution_key_slots', 'canonical shared field name for task scope slots'),
  ('fld_W9NA62KA', 'field', 'TASK_STATUS_SUMMARY', 'text', 'task_status_summary', NULL, 'maintenance_output_slots', 'canonical shared field name for task status summary slots'),
  ('fld_VTD4KDTM', 'field', 'TEMPORARY_NEW_NAMES', 'text', 'temporary_new_names', NULL, 'completion_receipt_slots', 'canonical shared field name for temporary new name slots'),
  ('fld_U27NM0BU', 'field', 'TEST_COMMANDS', 'text', 'test_commands', NULL, 'execution_key_slots', 'canonical shared field name for test command slots'),
  ('fld_0YVMMK1A', 'field', 'TEST_EXPECTATION', 'text', 'test_expectation', NULL, 'execution_key_slots', 'canonical shared field name for test expectation slots'),
  ('fld_YX5TMJN9', 'field', 'TEST_OUTPUT', 'text', 'test_output', NULL, 'completion_receipt_slots;acceptance_receipt_slots', 'canonical shared field name for test output slots'),
  ('fld_T5PSOYKO', 'field', 'TEST_STATUS', 'text', 'test_status', NULL, 'completion_receipt_slots;acceptance_receipt_slots', 'canonical shared field name for test status slots'),
  ('fld_ZGTS8P3D', 'field', 'WORKFLOW_IDENTITY', 'text', 'workflow_identity', NULL, 'execution_key_slots;completion_receipt_slots;acceptance_receipt_slots', 'canonical shared field name for workflow identity slots'),
  ('mns_B5N1K6XD', 'maintenance_status', 'MAINTENANCE_STATUS_BLOCKED', 'text', 'blocked', NULL, NULL, 'default shared maintenance status value when maintenance is blocked by a real constraint'),
  ('mns_L4T8Q2WP', 'maintenance_status', 'MAINTENANCE_STATUS_HEALTHY', 'text', 'healthy', NULL, NULL, 'default shared maintenance status value when the project is in healthy maintained shape'),
  ('mns_P7C3V9RA', 'maintenance_status', 'MAINTENANCE_STATUS_NEEDS_ATTENTION', 'text', 'needs_attention', NULL, NULL, 'default shared maintenance status value when maintenance found issues that need attention'),
  ('rep_H6S3V8LA', 'repo', 'TRADING_MAIN_REPO', 'text', 'trading-main', '/root/projects/trading-main', NULL, 'canonical repository entry for the trading-main project, including its repository root path'),
  ('rrd_V9H5C2KR', 'review_readiness', 'REVIEW_READINESS_BLOCKED', 'text', 'blocked', NULL, NULL, 'default shared review readiness value for work that is blocked from review'),
  ('rrd_W6P3N1TX', 'review_readiness', 'REVIEW_READINESS_NOT_READY', 'text', 'not_ready', NULL, NULL, 'default shared review readiness value for work that is not ready for review'),
  ('rrd_L2F8Q4MA', 'review_readiness', 'REVIEW_READINESS_READY', 'text', 'ready', NULL, NULL, 'default shared review readiness value for work that is ready for review'),
  ('scr_CV8R2M5J', 'script', 'REGISTRY_EXPORT_CURRENT_CSV_HELPER', 'text', 'registry/sql/apply-migrations.py --export-only', '/root/projects/trading-main/registry/sql/apply-migrations.py', 'registry/current.csv', 'maintenance helper command that exports the active trading_registry table to registry/current.csv'),
  ('scr_GK1D8P4Q', 'script', 'REGISTRY_GET_KEY_BY_ID_HELPER', 'text', 'RegistryReader.get_key_by_id', '/root/projects/trading-main/helpers/python/trading_registry/reader.py', 'helpers/python/trading_registry', 'official Python runtime helper that returns a registry item key or null by stable id'),
  ('scr_GH6V3T8N', 'script', 'REGISTRY_GET_PATH_BY_ID_HELPER', 'text', 'RegistryReader.get_path_by_id', '/root/projects/trading-main/helpers/python/trading_registry/reader.py', 'helpers/python/trading_registry', 'official Python runtime helper that returns a registry item path or null by stable id'),
  ('scr_GP2L7M9A', 'script', 'REGISTRY_GET_PAYLOAD_BY_ID_HELPER', 'text', 'RegistryReader.get_payload_by_id', '/root/projects/trading-main/helpers/python/trading_registry/reader.py', 'helpers/python/trading_registry', 'official Python runtime helper that returns a registry item payload or null by stable id'),
  ('scr_LS5Q2K7W', 'script', 'REGISTRY_LOAD_SECRET_TEXT_BY_CONFIG_ID_HELPER', 'text', 'SecretResolver.load_secret_text_by_config_id', '/root/projects/trading-main/helpers/python/trading_registry/secret_resolver.py', 'helpers/python/trading_registry', 'official Python runtime helper that resolves a config payload secret alias and returns trimmed secret text by stable config id'),
  ('tls_H1V8L4TE', 'task_lifecycle_state', 'TASK_LIFECYCLE_STATE_ACCEPTED', 'text', 'accepted', NULL, NULL, 'default shared task lifecycle state value for work that has been accepted'),
  ('tls_K5Q7F2MD', 'task_lifecycle_state', 'TASK_LIFECYCLE_STATE_BLOCKED', 'text', 'blocked', NULL, NULL, 'default shared task lifecycle state value for work that is blocked'),
  ('tls_C9T1G7WF', 'task_lifecycle_state', 'TASK_LIFECYCLE_STATE_CANCELLED', 'text', 'cancelled', NULL, NULL, 'default shared task lifecycle state value for work that has been cancelled'),
  ('tls_M4D6R8QJ', 'task_lifecycle_state', 'TASK_LIFECYCLE_STATE_CLOSED', 'text', 'closed', NULL, NULL, 'default shared task lifecycle state value for work that is closed'),
  ('tls_D4N8K2QW', 'task_lifecycle_state', 'TASK_LIFECYCLE_STATE_DESIGNING', 'text', 'designing', NULL, NULL, 'default shared task lifecycle state value for work that is still being designed'),
  ('tls_B6X2H5RA', 'task_lifecycle_state', 'TASK_LIFECYCLE_STATE_DISPATCHED', 'text', 'dispatched', NULL, NULL, 'default shared task lifecycle state value for work that has been dispatched'),
  ('tls_T8J4W1NP', 'task_lifecycle_state', 'TASK_LIFECYCLE_STATE_EXECUTING', 'text', 'executing', NULL, NULL, 'default shared task lifecycle state value for work in active execution'),
  ('tls_R3C9Y6UA', 'task_lifecycle_state', 'TASK_LIFECYCLE_STATE_READY_FOR_ACCEPTANCE', 'text', 'ready_for_acceptance', NULL, NULL, 'default shared task lifecycle state value for work waiting for acceptance review'),
  ('tls_P7M3V9LC', 'task_lifecycle_state', 'TASK_LIFECYCLE_STATE_READY_TO_DISPATCH', 'text', 'ready_to_dispatch', NULL, NULL, 'default shared task lifecycle state value for work ready to hand to an executor'),
  ('tls_N7B2P5XK', 'task_lifecycle_state', 'TASK_LIFECYCLE_STATE_REJECTED', 'text', 'rejected', NULL, NULL, 'default shared task lifecycle state value for work that has been rejected'),
  ('trm_RXUP2T7D', 'term', 'CODEX', 'text', 'Coding executor used for bounded implementation tasks under OpenClaw supervision.', NULL, NULL, 'canonical shared definition for Codex in this workspace'),
  ('trm_5HE1ZLG6', 'term', 'OPENCLAW', 'text', 'Project sentinel and orchestration layer that owns project route, docs, dispatch, review, and acceptance.', NULL, NULL, 'canonical shared definition for OpenClaw'),
  ('trm_4F58616K', 'term', 'POSTGRESQL', 'text', 'Open-source relational database system used as the target engine for trading-main registry and related server-side data work.', NULL, NULL, 'canonical shared definition for PostgreSQL'),
  ('trm_S8M3B7VN', 'term', 'SMB', 'text', 'Server Message Block; network file-sharing protocol used for mounted or shared folders when needed.', NULL, NULL, 'canonical shared definition for SMB in the trading server environment'),
  ('trm_NBPU5J5P', 'term', 'SQL', 'text', 'Structured Query Language; the standard language for querying and managing relational databases.', NULL, NULL, 'canonical shared definition for SQL'),
  ('trm_T4X9L2QK', 'term', 'TAILSCALE', 'text', 'Mesh VPN used for private network connectivity between trusted devices and services.', NULL, NULL, 'canonical shared definition for Tailscale in the trading server environment'),
  ('trm_QLKAMITP', 'term', 'TRADING_MAIN_REGISTRY', 'text', 'Trading-main registry for trading-wide referenced values, approved outputs, source locators, status vocabularies, and approved terms.', NULL, NULL, 'canonical shared definition for trading-main registry'),
  ('tst_F6V1M5RA', 'test_status', 'TEST_STATUS_FAILED', 'text', 'failed', NULL, NULL, 'default shared test status value for failing verification'),
  ('tst_X5N1B4QJ', 'test_status', 'TEST_STATUS_NOT_REQUIRED', 'text', 'not_required', NULL, NULL, 'default shared test status value when verification was not required'),
  ('tst_P9C4T7XH', 'test_status', 'TEST_STATUS_NOT_RUN', 'text', 'not_run', NULL, NULL, 'default shared test status value when verification did not run'),
  ('tst_R2D6K8YL', 'test_status', 'TEST_STATUS_PARTIALLY_RUN', 'text', 'partially_run', NULL, NULL, 'default shared test status value when verification ran only partially'),
  ('tst_J3Q8L2NW', 'test_status', 'TEST_STATUS_PASSED', 'text', 'passed', NULL, NULL, 'default shared test status value for passing verification')
ON CONFLICT (id) DO UPDATE SET
  kind = EXCLUDED.kind,
  key = EXCLUDED.key,
  payload_format = EXCLUDED.payload_format,
  payload = EXCLUDED.payload,
  path = EXCLUDED.path,
  applies_to = EXCLUDED.applies_to,
  note = EXCLUDED.note;
