-- Register unified event database template fields and data kinds.
-- Target engine: PostgreSQL.

INSERT INTO trading_registry (id, kind, key, payload_format, payload, path, applies_to, note)
VALUES
  ('fld_EVT010', 'field', 'EVENT_ID', 'text', 'event_id', 'trading-data/storage/templates/data_kinds/events/README.md', 'trading_event_template;event_factor_template;event_analysis_report_template', 'stable random event identifier shared across event timeline rows, factor rows, and analysis report artifacts; do not encode timestamp/source semantics'),
  ('fld_EVT011', 'field', 'EVENT_SECURITY_ID', 'text', 'security_id', 'trading-data/storage/templates/data_kinds/events/README.md', 'trading_event_template;event_factor_template;event_analysis_report_template', 'canonical security or company identifier when available; symbol remains available separately for display/routing'),
  ('fld_EVT012', 'field', 'EVENT_SYMBOL', 'text', 'symbol', 'trading-data/storage/templates/data_kinds/events/README.md', 'trading_event_template;event_factor_template;event_analysis_report_template', 'primary tradable symbol for the event when one symbol is dominant'),
  ('fld_EVT013', 'field', 'EVENT_TIME_ET', 'text', 'event_time_et', 'trading-data/storage/templates/data_kinds/events/README.md', 'trading_event_template;event_factor_template', 'source publication or detection timestamp normalized to America/New_York; do not backfill from later observation times'),
  ('fld_EVT014', 'field', 'EVENT_EFFECTIVE_TIME_ET', 'text', 'effective_time_et', 'trading-data/storage/templates/data_kinds/events/README.md', 'trading_event_template;event_factor_template', 'earliest trading timestamp when the event is safely observable/actionable; required to prevent look-ahead leakage'),
  ('fld_EVT015', 'field', 'EVENT_TYPE', 'text', 'event_type', 'trading-data/storage/templates/data_kinds/events/README.md', 'trading_event_template;event_factor_template;event_analysis_report_template', 'normalized event taxonomy label such as equity_financial_report_event, equity_news_event, option_activity_event, equity_ma_event, or equity_offering_event'),
  ('fld_EVT016', 'field', 'EVENT_SOURCE_TYPE', 'text', 'source_type', 'trading-data/storage/templates/data_kinds/events/README.md', 'trading_event_template;event_analysis_report_template', 'source family for the event such as sec_filing, news_article, option_market_activity, exchange_notice, or macro_release'),
  ('fld_EVT017', 'field', 'EVENT_SOURCE_REF', 'text', 'source_ref', 'trading-data/storage/templates/data_kinds/events/README.md', 'trading_event_template;event_analysis_report_template', 'compact source reference such as SEC accession number, article id/url, option event detail id, or release-calendar id'),
  ('fld_EVT018', 'field', 'EVENT_SOURCE_URL', 'text', 'source_url', 'trading-data/storage/templates/data_kinds/events/README.md', 'trading_event_template;event_analysis_report_template', 'official/source URL or local artifact URL for the original source evidence'),
  ('fld_EVT019', 'field', 'EVENT_TITLE', 'text', 'title', 'trading-data/storage/templates/data_kinds/events/README.md', 'trading_event_template;event_analysis_report_template', 'short human title/headline for the event'),
  ('fld_EVT020', 'field', 'EVENT_SUMMARY', 'text', 'summary', 'trading-data/storage/templates/data_kinds/events/README.md', 'trading_event_template;event_analysis_report_template', 'short human-readable summary of the event, not a long agent report'),
  ('fld_EVT021', 'field', 'EVENT_ANALYSIS_REPORT_URL', 'text', 'analysis_report_url', 'trading-data/storage/templates/data_kinds/events/README.md', 'trading_event_template;event_factor_template', 'local or object-store URL pointing to the long-form agent/model analysis report artifact for this event'),
  ('fld_EVT022', 'field', 'EVENT_ANALYSIS_STATUS', 'text', 'analysis_status', 'trading-data/storage/templates/data_kinds/events/README.md', 'trading_event_template;event_analysis_report_template', 'analysis lifecycle status such as not_requested, pending, succeeded, failed, or superseded'),
  ('fld_EVT023', 'field', 'EVENT_DIRECTION_SCORE', 'text', 'direction_score', 'trading-data/storage/templates/data_kinds/events/README.md', 'event_factor_template', 'numeric directional estimate where positive is favorable and negative is unfavorable for the primary symbol'),
  ('fld_EVT024', 'field', 'EVENT_MAGNITUDE_SCORE', 'text', 'magnitude_score', 'trading-data/storage/templates/data_kinds/events/README.md', 'event_factor_template', 'numeric estimate of event impact size normalized enough for model ingestion'),
  ('fld_EVT025', 'field', 'EVENT_SURPRISE_SCORE', 'text', 'surprise_score', 'trading-data/storage/templates/data_kinds/events/README.md', 'event_factor_template', 'numeric estimate of how far the event differs from prior expectations or baseline behavior'),
  ('fld_EVT026', 'field', 'EVENT_NOVELTY_SCORE', 'text', 'novelty_score', 'trading-data/storage/templates/data_kinds/events/README.md', 'event_factor_template', 'numeric estimate of non-duplication/new information versus recent similar events'),
  ('fld_EVT027', 'field', 'EVENT_RELEVANCE_SCORE', 'text', 'relevance_score', 'trading-data/storage/templates/data_kinds/events/README.md', 'event_factor_template', 'numeric estimate of how directly the event applies to the primary security'),
  ('fld_EVT028', 'field', 'EVENT_CREDIBILITY_SCORE', 'text', 'credibility_score', 'trading-data/storage/templates/data_kinds/events/README.md', 'event_factor_template', 'numeric estimate of source reliability and evidentiary strength'),
  ('fld_EVT029', 'field', 'EVENT_PRICE_IN_SCORE', 'text', 'price_in_score', 'trading-data/storage/templates/data_kinds/events/README.md', 'event_factor_template', 'numeric estimate of pre-event market reaction/price-in penalty computed only from observable pre-effective-time data'),
  ('fld_EVT030', 'field', 'EVENT_REACTION_SCORE', 'text', 'reaction_score', 'trading-data/storage/templates/data_kinds/events/README.md', 'event_factor_template', 'numeric immediate market-reaction score only when the trading decision time can observe that reaction'),
  ('fld_EVT031', 'field', 'EVENT_FACTOR_AS_OF_ET', 'text', 'factor_as_of_et', 'trading-data/storage/templates/data_kinds/events/README.md', 'event_factor_template', 'timestamp in America/New_York when event factor values were generated or became available'),
  ('fld_EVT032', 'field', 'EVENT_FACTOR_VERSION', 'text', 'factor_version', 'trading-data/storage/templates/data_kinds/events/README.md', 'event_factor_template', 'version or model identifier for event factor extraction/scoring logic'),
  ('fld_EVT033', 'field', 'EVENT_REPORT_ID', 'text', 'report_id', 'trading-data/storage/templates/data_kinds/events/README.md', 'event_analysis_report_template', 'stable random identifier for one analysis report artifact associated with an event'),
  ('fld_EVT034', 'field', 'EVENT_REPORT_URL', 'text', 'report_url', 'trading-data/storage/templates/data_kinds/events/README.md', 'event_analysis_report_template', 'local or object-store URL for the Markdown or human-readable analysis report artifact'),
  ('fld_EVT035', 'field', 'EVENT_REPORT_JSON_URL', 'text', 'report_json_url', 'trading-data/storage/templates/data_kinds/events/README.md', 'event_analysis_report_template', 'local or object-store URL for the structured JSON sidecar extracted from the analysis report'),
  ('fld_EVT036', 'field', 'EVENT_ANALYSIS_MODEL', 'text', 'analysis_model', 'trading-data/storage/templates/data_kinds/events/README.md', 'event_analysis_report_template', 'model or agent identifier that produced the analysis report'),
  ('fld_EVT037', 'field', 'EVENT_ANALYSIS_GENERATED_AT_ET', 'text', 'analysis_generated_at_et', 'trading-data/storage/templates/data_kinds/events/README.md', 'event_analysis_report_template', 'analysis report generation timestamp normalized to America/New_York'),
  ('fld_EVT038', 'field', 'EVENT_TAXONOMY_CONTEXT', 'text', 'taxonomy_context', 'trading-data/storage/templates/data_kinds/events/README.md', 'trading_event_template;event_analysis_report_template', 'JSON text with source-specific taxonomy context such as SEC form/items, news category, or option trigger names'),
  ('dki_TREVT001', 'data_kind', 'TRADING_EVENT', 'text', 'trading_event', 'trading-data/storage/templates/data_kinds/events/trading_event.preview.csv', 'event_database', 'Unified event database row across financial reports, SEC corporate events, news, macro releases, option activity, and market anomalies; stores facts and artifact links only'),
  ('dki_TREVT002', 'data_kind', 'EVENT_FACTOR', 'text', 'event_factor', 'trading-data/storage/templates/data_kinds/events/event_factor.preview.csv', 'event_database', 'Numeric model-facing event factor row derived from one trading_event; keeps scoring features separate from source facts and future labels'),
  ('dki_TREVT003', 'data_kind', 'EVENT_ANALYSIS_REPORT', 'text', 'event_analysis_report', 'trading-data/storage/templates/data_kinds/events/event_analysis_report.preview.csv', 'event_database', 'Index row for long-form agent/model analysis report artifacts and structured JSON sidecars referenced by trading_event')
ON CONFLICT (id) DO UPDATE
SET
  kind = EXCLUDED.kind,
  key = EXCLUDED.key,
  payload_format = EXCLUDED.payload_format,
  payload = EXCLUDED.payload,
  path = EXCLUDED.path,
  applies_to = EXCLUDED.applies_to,
  note = EXCLUDED.note;
