-- Register initial source-availability data kinds for trading-data.
-- Target engine: PostgreSQL.

UPDATE trading_registry
SET
  payload = 'FRED/St. Louis Fed/ALFRED-native macro data provider used only for unique or explicitly approved FRED-native research series/groups',
  note = 'approved provider terminology; FRED must not duplicate official BLS/BEA/Census/Treasury acquisition paths unless an exception is explicitly reviewed'
WHERE key = 'FRED';

INSERT INTO trading_registry (id, kind, key, payload_format, payload, path, applies_to, note)
VALUES
  ('dki_TOYRS7UZ', 'data_kind', 'EQUITY_BAR', 'text', 'equity_bar', 'https://docs.alpaca.markets/reference/stockbars', 'alpaca_bars', 'Alpaca stock/ETF OHLCV bars; entitlement/feed validation required at runtime'),
  ('dki_ELPMPT7W', 'data_kind', 'EQUITY_TRADE', 'text', 'equity_trade', 'https://docs.alpaca.markets/reference/stocktrades', 'alpaca_quotes_trades', 'Alpaca stock/ETF trade prints'),
  ('dki_H58O19IF', 'data_kind', 'EQUITY_QUOTE', 'text', 'equity_quote', 'https://docs.alpaca.markets/reference/stockquotes-1', 'alpaca_quotes_trades', 'Alpaca stock/ETF NBBO/quote records'),
  ('dki_4OEED0FT', 'data_kind', 'EQUITY_SNAPSHOT', 'text', 'equity_snapshot', 'https://docs.alpaca.markets/reference/stocksnapshots-1', 'alpaca_quotes_trades', 'Alpaca stock/ETF snapshot records when accepted for use'),
  ('dki_1KW5CB9R', 'data_kind', 'EQUITY_NEWS', 'text', 'equity_news', 'https://docs.alpaca.markets/reference/news-3', 'alpaca_news', 'Alpaca stock/ETF news records and article metadata'),
  ('dki_O9BGKU9V', 'data_kind', 'CRYPTO_BAR', 'text', 'crypto_bar', 'https://www.okx.com/docs-v5/en/', 'okx_bars', 'OKX crypto candlestick/bar records'),
  ('dki_BFOOT2KD', 'data_kind', 'CRYPTO_TRADE', 'text', 'crypto_trade', 'https://www.okx.com/docs-v5/en/', 'okx_bars', 'OKX crypto trade records if later accepted beyond bars'),
  ('dki_UV1LV9WE', 'data_kind', 'CRYPTO_QUOTE', 'text', 'crypto_quote', 'https://www.okx.com/docs-v5/en/', 'okx_bars', 'OKX crypto quote/ticker records if later accepted beyond bars'),
  ('dki_4LDCM9Q8', 'data_kind', 'CRYPTO_ORDER_BOOK', 'text', 'crypto_order_book', 'https://www.okx.com/docs-v5/en/', 'okx_bars', 'OKX crypto order book/depth records if later accepted beyond bars'),
  ('dki_BWQ5ICU7', 'data_kind', 'OPTION_CONTRACT', 'text', 'option_contract', 'https://http-docs.thetadata.us/', 'thetadata_option_1m_bundle;thetadata_option_snapshot_bundle', 'ThetaData option contract/reference records'),
  ('dki_2222F63W', 'data_kind', 'OPTION_TRADE', 'text', 'option_trade', 'https://http-docs.thetadata.us/', 'thetadata_option_1m_bundle', 'ThetaData option trade records'),
  ('dki_CK3CV9TH', 'data_kind', 'OPTION_QUOTE', 'text', 'option_quote', 'https://http-docs.thetadata.us/', 'thetadata_option_1m_bundle', 'ThetaData option quote records'),
  ('dki_O7F5GJCD', 'data_kind', 'OPTION_NBBO', 'text', 'option_nbbo', 'https://http-docs.thetadata.us/', 'thetadata_option_1m_bundle', 'ThetaData option NBBO quote records'),
  ('dki_V93OLXTY', 'data_kind', 'OPTION_OHLC', 'text', 'option_ohlc', 'https://http-docs.thetadata.us/', 'thetadata_option_1m_bundle', 'ThetaData option OHLC records'),
  ('dki_6MTHFL7Q', 'data_kind', 'OPTION_EOD', 'text', 'option_eod', 'https://http-docs.thetadata.us/', 'thetadata_option_1m_bundle', 'ThetaData option end-of-day records'),
  ('dki_CHECOD4I', 'data_kind', 'OPTION_OPEN_INTEREST', 'text', 'option_open_interest', 'https://http-docs.thetadata.us/', 'thetadata_option_1m_bundle;thetadata_option_snapshot_bundle', 'ThetaData option open interest records'),
  ('dki_1IKW20PE', 'data_kind', 'OPTION_IMPLIED_VOLATILITY', 'text', 'option_implied_volatility', 'https://http-docs.thetadata.us/', 'thetadata_option_1m_bundle;thetadata_option_snapshot_bundle', 'ThetaData option implied volatility records'),
  ('dki_YY7IBQ8C', 'data_kind', 'OPTION_GREEKS_FIRST_ORDER', 'text', 'option_greeks_first_order', 'https://http-docs.thetadata.us/', 'thetadata_option_1m_bundle;thetadata_option_snapshot_bundle', 'ThetaData first-order Greeks'),
  ('dki_PZNI1XUP', 'data_kind', 'OPTION_GREEKS_SECOND_ORDER', 'text', 'option_greeks_second_order', 'https://http-docs.thetadata.us/', 'thetadata_option_1m_bundle', 'ThetaData second-order Greeks'),
  ('dki_E5R4G5KB', 'data_kind', 'OPTION_GREEKS_THIRD_ORDER', 'text', 'option_greeks_third_order', 'https://http-docs.thetadata.us/', 'thetadata_option_1m_bundle', 'ThetaData third-order Greeks'),
  ('dki_GFV59VYO', 'data_kind', 'OPTION_TRADE_GREEKS', 'text', 'option_trade_greeks', 'https://http-docs.thetadata.us/', 'thetadata_option_1m_bundle', 'ThetaData trade Greeks records'),
  ('dki_6CW1NB0H', 'data_kind', 'OPTION_SNAPSHOT', 'text', 'option_snapshot', 'https://http-docs.thetadata.us/', 'thetadata_option_snapshot_bundle', 'ThetaData requested-time option snapshot records'),
  ('dki_4SBQMF2Y', 'data_kind', 'SEC_SUBMISSION', 'text', 'sec_submission', 'https://www.sec.gov/search-filings/edgar-application-programming-interfaces', 'sec_company_financials', 'SEC EDGAR submissions and filing-history JSON'),
  ('dki_PBST7F0X', 'data_kind', 'SEC_COMPANY_FACT', 'text', 'sec_company_fact', 'https://www.sec.gov/search-filings/edgar-application-programming-interfaces', 'sec_company_financials', 'SEC companyfacts XBRL facts by CIK'),
  ('dki_FDDPJVLF', 'data_kind', 'SEC_COMPANY_CONCEPT', 'text', 'sec_company_concept', 'https://www.sec.gov/search-filings/edgar-application-programming-interfaces', 'sec_company_financials', 'SEC companyconcept facts for one taxonomy/tag'),
  ('dki_D21L7FWL', 'data_kind', 'SEC_XBRL_FRAME', 'text', 'sec_xbrl_frame', 'https://www.sec.gov/search-filings/edgar-application-programming-interfaces', 'sec_company_financials', 'SEC frames API records for cross-company XBRL concept periods'),
  ('dki_OFH0JXSP', 'data_kind', 'SEC_FILING_DOCUMENT', 'text', 'sec_filing_document', 'https://www.sec.gov/search-filings/edgar-application-programming-interfaces', 'sec_company_financials', 'SEC filing document metadata/content references when accepted'),
  ('dki_YDPFX3FL', 'data_kind', 'ETF_HOLDING', 'text', 'etf_holding', NULL, 'etf_holdings', 'ETF issuer-published constituent holding row'),
  ('dki_NFRKHNJO', 'data_kind', 'ETF_HOLDINGS_SNAPSHOT', 'text', 'etf_holdings_snapshot', NULL, 'etf_holdings', 'ETF issuer-published holdings snapshot for one fund/as-of date'),
  ('dki_LU1O02ID', 'data_kind', 'ETF_FUND_METADATA', 'text', 'etf_fund_metadata', NULL, 'etf_holdings', 'ETF issuer fund metadata used with holdings files'),
  ('dki_H1NIJOXE', 'data_kind', 'ETF_CONSTITUENT_WEIGHT', 'text', 'etf_constituent_weight', NULL, 'etf_holdings', 'ETF constituent weight/proportion value'),
  ('dki_KN1B2Z22', 'data_kind', 'FOMC_MEETING', 'text', 'fomc_meeting', 'https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm', 'calendar_discovery', 'Official FOMC meeting date/event'),
  ('dki_2CAKSIGD', 'data_kind', 'FOMC_STATEMENT', 'text', 'fomc_statement', 'https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm', 'calendar_discovery', 'Official FOMC statement reference'),
  ('dki_UKQ6JXO2', 'data_kind', 'FOMC_MINUTES', 'text', 'fomc_minutes', 'https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm', 'calendar_discovery', 'Official FOMC minutes reference'),
  ('dki_7CVERDFO', 'data_kind', 'FOMC_SEP', 'text', 'fomc_sep', 'https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm', 'calendar_discovery', 'Official FOMC Summary of Economic Projections marker/reference'),
  ('dki_I38ZFCHC', 'data_kind', 'ECONOMIC_RELEASE_CALENDAR', 'text', 'economic_release_calendar', NULL, 'calendar_discovery;macro_data', 'Official macro release calendar source records'),
  ('dki_FE2I3H05', 'data_kind', 'ECONOMIC_RELEASE_EVENT', 'text', 'economic_release_event', NULL, 'calendar_discovery;macro_data', 'One official macro release event with timing metadata'),
  ('dki_0JENZ8M2', 'data_kind', 'MACRO_BLS_CPI', 'text', 'macro_bls_cpi', 'https://www.bls.gov/developers/', 'macro_data', 'BLS CPI/C-CPI data via official BLS source'),
  ('dki_C4S8D35Y', 'data_kind', 'MACRO_BLS_PPI', 'text', 'macro_bls_ppi', 'https://www.bls.gov/developers/', 'macro_data', 'BLS Producer Price Index data via official BLS source'),
  ('dki_Y9WLYZ3V', 'data_kind', 'MACRO_BLS_IMPORT_EXPORT_PRICES', 'text', 'macro_bls_import_export_prices', 'https://www.bls.gov/developers/', 'macro_data', 'BLS import/export price index data via official BLS source'),
  ('dki_8BHQTI3X', 'data_kind', 'MACRO_BLS_EMPLOYMENT_PAYROLLS', 'text', 'macro_bls_employment_payrolls', 'https://www.bls.gov/developers/', 'macro_data', 'BLS CES payrolls/earnings/hours data via official BLS source'),
  ('dki_KHJE6LL4', 'data_kind', 'MACRO_BLS_LABOR_FORCE', 'text', 'macro_bls_labor_force', 'https://www.bls.gov/developers/', 'macro_data', 'BLS CPS labor force/unemployment data via official BLS source'),
  ('dki_VQ1G3MK4', 'data_kind', 'MACRO_BLS_JOLTS', 'text', 'macro_bls_jolts', 'https://www.bls.gov/developers/', 'macro_data', 'BLS JOLTS data via official BLS source'),
  ('dki_5KYL7M8Q', 'data_kind', 'MACRO_BLS_ECI', 'text', 'macro_bls_eci', 'https://www.bls.gov/developers/', 'macro_data', 'BLS Employment Cost Index data via official BLS source'),
  ('dki_876T4EY8', 'data_kind', 'MACRO_BLS_PRODUCTIVITY', 'text', 'macro_bls_productivity', 'https://www.bls.gov/developers/', 'macro_data', 'BLS productivity data via official BLS source'),
  ('dki_0Z8EQHJ1', 'data_kind', 'MACRO_CENSUS_RETAIL_SALES', 'text', 'macro_census_retail_sales', 'https://www.census.gov/data/developers/data-sets.html', 'macro_data', 'Census retail sales / economic indicators data via official Census source'),
  ('dki_WU9JQTH8', 'data_kind', 'MACRO_CENSUS_WHOLESALE_TRADE', 'text', 'macro_census_wholesale_trade', 'https://www.census.gov/data/developers/data-sets.html', 'macro_data', 'Census wholesale trade data via official Census source'),
  ('dki_A76RQWEN', 'data_kind', 'MACRO_CENSUS_MANUFACTURING_ORDERS', 'text', 'macro_census_manufacturing_orders', 'https://www.census.gov/data/developers/data-sets.html', 'macro_data', 'Census manufacturers shipments inventories and orders data via official Census source'),
  ('dki_T6I7V84J', 'data_kind', 'MACRO_CENSUS_DURABLE_GOODS', 'text', 'macro_census_durable_goods', 'https://www.census.gov/data/developers/data-sets.html', 'macro_data', 'Census durable goods data via official Census source'),
  ('dki_F7FGVKD2', 'data_kind', 'MACRO_CENSUS_CONSTRUCTION_SPENDING', 'text', 'macro_census_construction_spending', 'https://www.census.gov/data/developers/data-sets.html', 'macro_data', 'Census construction spending data via official Census source'),
  ('dki_BRBI43WK', 'data_kind', 'MACRO_CENSUS_HOUSING_CONSTRUCTION', 'text', 'macro_census_housing_construction', 'https://www.census.gov/data/developers/data-sets.html', 'macro_data', 'Census housing starts permits completions data via official Census source'),
  ('dki_2RCM6FD8', 'data_kind', 'MACRO_CENSUS_NEW_HOME_SALES', 'text', 'macro_census_new_home_sales', 'https://www.census.gov/data/developers/data-sets.html', 'macro_data', 'Census new home sales data via official Census source'),
  ('dki_LY8ASAXO', 'data_kind', 'MACRO_CENSUS_BUSINESS_FORMATION', 'text', 'macro_census_business_formation', 'https://www.census.gov/data/developers/data-sets.html', 'macro_data', 'Census business formation data via official Census source'),
  ('dki_C6QSASTF', 'data_kind', 'MACRO_CENSUS_INTERNATIONAL_TRADE', 'text', 'macro_census_international_trade', 'https://www.census.gov/data/developers/data-sets.html', 'macro_data', 'Census international trade data via official Census source'),
  ('dki_6WZUNS4N', 'data_kind', 'MACRO_BEA_NIPA', 'text', 'macro_bea_nipa', 'https://apps.bea.gov/api/data', 'macro_data', 'BEA NIPA/GDP accounts data via official BEA source'),
  ('dki_QYOJP5KI', 'data_kind', 'MACRO_BEA_PCE_INCOME_OUTLAYS', 'text', 'macro_bea_pce_income_outlays', 'https://apps.bea.gov/api/data', 'macro_data', 'BEA personal consumption expenditures and income/outlays data via official BEA source'),
  ('dki_SDUDHZ65', 'data_kind', 'MACRO_BEA_GDP_BY_INDUSTRY', 'text', 'macro_bea_gdp_by_industry', 'https://apps.bea.gov/api/data', 'macro_data', 'BEA GDP by industry data via official BEA source'),
  ('dki_AGPLL9NM', 'data_kind', 'MACRO_BEA_REGIONAL', 'text', 'macro_bea_regional', 'https://apps.bea.gov/api/data', 'macro_data', 'BEA regional GDP income and PCE data via official BEA source'),
  ('dki_TK3I0XOK', 'data_kind', 'MACRO_BEA_INTERNATIONAL_ACCOUNTS', 'text', 'macro_bea_international_accounts', 'https://apps.bea.gov/api/data', 'macro_data', 'BEA international accounts data via official BEA source'),
  ('dki_L378HBRW', 'data_kind', 'MACRO_BEA_FIXED_ASSETS', 'text', 'macro_bea_fixed_assets', 'https://apps.bea.gov/api/data', 'macro_data', 'BEA fixed assets data via official BEA source'),
  ('dki_VT4PLMXK', 'data_kind', 'MACRO_TREASURY_DEBT', 'text', 'macro_treasury_debt', 'https://fiscaldata.treasury.gov/api-documentation/', 'macro_data', 'U.S. Treasury Fiscal Data federal debt datasets'),
  ('dki_7F4VNB2F', 'data_kind', 'MACRO_TREASURY_DTS', 'text', 'macro_treasury_dts', 'https://fiscaldata.treasury.gov/api-documentation/', 'macro_data', 'U.S. Treasury Fiscal Data Daily Treasury Statement datasets'),
  ('dki_69RQGUNC', 'data_kind', 'MACRO_TREASURY_MTS', 'text', 'macro_treasury_mts', 'https://fiscaldata.treasury.gov/api-documentation/', 'macro_data', 'U.S. Treasury Fiscal Data Monthly Treasury Statement datasets'),
  ('dki_JS3IVF3L', 'data_kind', 'MACRO_TREASURY_INTEREST_RATES', 'text', 'macro_treasury_interest_rates', 'https://fiscaldata.treasury.gov/api-documentation/', 'macro_data', 'U.S. Treasury Fiscal Data interest rate datasets'),
  ('dki_3HLBSWLF', 'data_kind', 'MACRO_TREASURY_INTEREST_EXPENSE', 'text', 'macro_treasury_interest_expense', 'https://fiscaldata.treasury.gov/api-documentation/', 'macro_data', 'U.S. Treasury Fiscal Data interest expense datasets'),
  ('dki_NN4RN3R8', 'data_kind', 'MACRO_FRED_NATIVE', 'text', 'macro_fred_native', 'https://fred.stlouisfed.org/docs/api/fred/', 'macro_data', 'FRED/St. Louis Fed native or explicitly approved FRED-native research series/groups only'),
  ('dki_5XDMM95N', 'data_kind', 'MACRO_ALFRED_VINTAGE', 'text', 'macro_alfred_vintage', 'https://fred.stlouisfed.org/docs/api/fred/alfred.html', 'macro_data', 'ALFRED/FRED real-time vintage observations; duplicate official-source exceptions require review'),
  ('dki_HBY2CJXZ', 'data_kind', 'MACRO_RELEASE_CALENDAR', 'text', 'macro_release_calendar', NULL, 'macro_data;calendar_discovery', 'Official macro release schedule/calendar data')
ON CONFLICT (id) DO UPDATE
SET
  kind = EXCLUDED.kind,
  key = EXCLUDED.key,
  payload_format = EXCLUDED.payload_format,
  payload = EXCLUDED.payload,
  path = EXCLUDED.path,
  applies_to = EXCLUDED.applies_to,
  note = EXCLUDED.note;
