-- Register model-input bundle boundaries and derived data products required by the seven-layer model architecture.
-- Target engine: PostgreSQL.

INSERT INTO trading_registry (id, kind, key, payload_format, payload, path, applies_to, artifact_sync_policy, note)
VALUES
  ('dbu_MRGINPUT', 'data_bundle', 'MARKET_REGIME_MODEL_INPUTS', 'text', 'market_regime_model_inputs', 'trading-data/docs/11_model_inputs.md', 'trading-data;trading-model;market_regime_model', 'sync_artifact', 'Input data organization bundle for MarketRegimeModel; primarily ETF/broad-market OHLCV bars, cross-asset ETF baskets, ratios, volatility, and liquidity-safe market-state features'),
  ('dbu_SECINPUT', 'data_bundle', 'SECURITY_SELECTION_MODEL_INPUTS', 'text', 'security_selection_model_inputs', 'trading-data/docs/11_model_inputs.md', 'trading-data;trading-model;security_selection_model', 'sync_artifact', 'Input data organization bundle for SecuritySelectionModel; combines MarketRegimeModel outputs, ETF holdings, stock_etf_exposure, equity bars/liquidity, optionability summaries, and event exclusions'),
  ('dbu_STRINPUT', 'data_bundle', 'STRATEGY_SELECTION_MODEL_INPUTS', 'text', 'strategy_selection_model_inputs', 'trading-data/docs/11_model_inputs.md', 'trading-data;trading-model;strategy_selection_model', 'sync_artifact', 'Input data organization bundle for StrategySelectionModel; equities use Alpaca bars/liquidity and crypto uses OKX bars/liquidity, conditioned on selected candidate symbols'),
  ('dbu_TRQINPUT', 'data_bundle', 'TRADE_QUALITY_MODEL_INPUTS', 'text', 'trade_quality_model_inputs', 'trading-data/docs/11_model_inputs.md', 'trading-data;trading-model;trade_quality_model', 'sync_artifact', 'Input data organization bundle for TradeQualityModel; consumes candidate signals and features from upstream model layers rather than introducing a new raw provider'),
  ('dbu_OPTINPUT', 'data_bundle', 'OPTION_EXPRESSION_MODEL_INPUTS', 'text', 'option_expression_model_inputs', 'trading-data/docs/11_model_inputs.md', 'trading-data;trading-model;option_expression_model', 'sync_artifact', 'Input data organization bundle for OptionExpressionModel V1; option chain snapshots, option bars/contract tracking, IV/Greeks/liquidity, and upstream signal forecasts for long call/long put selection only'),
  ('dbu_EVTINPUT', 'data_bundle', 'EVENT_OVERLAY_MODEL_INPUTS', 'text', 'event_overlay_model_inputs', 'trading-data/docs/11_model_inputs.md', 'trading-data;trading-model;event_overlay_model', 'sync_artifact', 'Input data organization bundle for EventOverlayModel; GDELT, SEC, Trading Economics, macro release events, option activity, equity abnormal activity, and stock/macro/event proximity features'),
  ('dbu_PRKINPUT', 'data_bundle', 'PORTFOLIO_RISK_MODEL_INPUTS', 'text', 'portfolio_risk_model_inputs', 'trading-data/docs/11_model_inputs.md', 'trading-data;trading-model;portfolio_risk_model', 'sync_artifact', 'Input data organization bundle for PortfolioRiskModel; requires option contract data plus portfolio/account state, positions, fills, PnL, exposures, limits, and execution-gate state from execution/account systems'),

  ('dki_STKETFEX', 'data_kind', 'STOCK_ETF_EXPOSURE', 'text', 'stock_etf_exposure', 'trading-data/storage/templates/data_kinds/model_inputs/stock_etf_exposure.preview.csv', 'security_selection_model_inputs;etf_holdings', 'sync_artifact', 'Derived point-in-time stock-to-ETF exposure row used to transmit ETF/sector/theme scores into SecuritySelectionModel candidate selection'),
  ('dki_EQABNACT', 'data_kind', 'EQUITY_ABNORMAL_ACTIVITY_EVENT', 'text', 'equity_abnormal_activity_event', 'trading-data/storage/templates/data_kinds/events/equity_abnormal_activity_event.preview.csv', 'event_overlay_model_inputs;alpaca_bars;alpaca_liquidity;event_database', 'sync_artifact', 'Derived event-style row for abnormal stock/ETF price, volume, relative-strength, gap, or liquidity activity feeding EventOverlayModel'),

  ('fld_STKEX001', 'field', 'STOCK_ETF_EXPOSURE_AS_OF_DATE', 'field_name', 'as_of_date', 'trading-data/storage/templates/data_kinds/model_inputs/stock_etf_exposure.preview.csv', 'stock_etf_exposure_template', 'sync_artifact', 'Date for the point-in-time stock-to-ETF exposure calculation'),
  ('fld_STKEX002', 'field', 'STOCK_ETF_EXPOSURE_SYMBOL', 'field_name', 'symbol', 'trading-data/storage/templates/data_kinds/model_inputs/stock_etf_exposure.preview.csv', 'stock_etf_exposure_template', 'sync_artifact', 'Stock or tradable equity symbol whose ETF exposure vector is represented'),
  ('fld_STKEX003', 'field', 'STOCK_ETF_EXPOSED_ETFS', 'field_name', 'exposed_etfs', 'trading-data/storage/templates/data_kinds/model_inputs/stock_etf_exposure.preview.csv', 'stock_etf_exposure_template', 'sync_artifact', 'Semicolon-separated or JSON-text ETF symbols containing the stock as a constituent'),
  ('fld_STKEX004', 'field', 'STOCK_ETF_TOP_EXPOSURE_ETF', 'field_name', 'top_exposure_etf', 'trading-data/storage/templates/data_kinds/model_inputs/stock_etf_exposure.preview.csv', 'stock_etf_exposure_template', 'sync_artifact', 'ETF with the largest or most relevant exposure weight for this stock on the exposure date'),
  ('fld_STKEX005', 'field', 'STOCK_ETF_TOTAL_EXPOSURE_SCORE', 'field_name', 'total_etf_exposure_score', 'trading-data/storage/templates/data_kinds/model_inputs/stock_etf_exposure.preview.csv', 'stock_etf_exposure_template', 'sync_artifact', 'Aggregated ETF exposure score across selected ETF basket memberships'),
  ('fld_STKEX006', 'field', 'STOCK_ETF_WEIGHTED_SECTOR_SCORE', 'field_name', 'weighted_sector_score', 'trading-data/storage/templates/data_kinds/model_inputs/stock_etf_exposure.preview.csv', 'stock_etf_exposure_template', 'sync_artifact', 'SecuritySelectionModel input score transmitting current sector ETF regime/rotation strength to this stock'),
  ('fld_STKEX007', 'field', 'STOCK_ETF_WEIGHTED_THEME_SCORE', 'field_name', 'weighted_theme_score', 'trading-data/storage/templates/data_kinds/model_inputs/stock_etf_exposure.preview.csv', 'stock_etf_exposure_template', 'sync_artifact', 'SecuritySelectionModel input score transmitting current thematic ETF strength to this stock'),
  ('fld_STKEX008', 'field', 'STOCK_ETF_STYLE_TAGS', 'field_name', 'style_tags', 'trading-data/storage/templates/data_kinds/model_inputs/stock_etf_exposure.preview.csv', 'stock_etf_exposure_template', 'sync_artifact', 'Semicolon-separated or JSON-text style tags such as semiconductor, AI, defensive, high_beta, or large_cap_growth'),
  ('fld_STKEX009', 'field', 'STOCK_ETF_SOURCE_ETF_COUNT', 'field_name', 'source_etf_count', 'trading-data/storage/templates/data_kinds/model_inputs/stock_etf_exposure.preview.csv', 'stock_etf_exposure_template', 'sync_artifact', 'Count of ETF holdings snapshots contributing to this exposure row'),
  ('fld_STKEX010', 'field', 'STOCK_ETF_SOURCE_SNAPSHOT_REFS', 'field_name', 'source_snapshot_refs', 'trading-data/storage/templates/data_kinds/model_inputs/stock_etf_exposure.preview.csv', 'stock_etf_exposure_template', 'sync_artifact', 'Source ETF holdings snapshot references used to build this exposure row'),
  ('fld_STKEX011', 'field', 'STOCK_ETF_AVAILABLE_TIME_ET', 'field_name', 'available_time_et', 'trading-data/storage/templates/data_kinds/model_inputs/stock_etf_exposure.preview.csv', 'stock_etf_exposure_template', 'sync_artifact', 'Earliest America/New_York timestamp when this exposure row is available for model use'),

  ('fld_ABN001', 'field', 'ABNORMAL_ACTIVITY_TYPE', 'field_name', 'abnormal_activity_type', 'trading-data/storage/templates/data_kinds/events/equity_abnormal_activity_event.preview.csv', 'equity_abnormal_activity_event_template', 'sync_artifact', 'Abnormal equity activity type such as return_zscore, volume_spike, sector_relative_move, gap, or liquidity_spread'),
  ('fld_ABN002', 'field', 'ABNORMAL_ACTIVITY_EVIDENCE_WINDOW', 'field_name', 'evidence_window', 'trading-data/storage/templates/data_kinds/events/equity_abnormal_activity_event.preview.csv', 'equity_abnormal_activity_event_template', 'sync_artifact', 'JSON text or compact descriptor for the time window used to measure abnormal equity activity'),
  ('fld_ABN003', 'field', 'RETURN_ZSCORE', 'field_name', 'return_zscore', 'trading-data/storage/templates/data_kinds/events/equity_abnormal_activity_event.preview.csv', 'equity_abnormal_activity_event_template', 'sync_artifact', 'Return z-score over the abnormal activity evidence window'),
  ('fld_ABN004', 'field', 'VOLUME_ZSCORE', 'field_name', 'volume_zscore', 'trading-data/storage/templates/data_kinds/events/equity_abnormal_activity_event.preview.csv', 'equity_abnormal_activity_event_template', 'sync_artifact', 'Volume z-score over the abnormal activity evidence window'),
  ('fld_ABN005', 'field', 'RELATIVE_STRENGTH_ZSCORE', 'field_name', 'relative_strength_zscore', 'trading-data/storage/templates/data_kinds/events/equity_abnormal_activity_event.preview.csv', 'equity_abnormal_activity_event_template', 'sync_artifact', 'Relative-strength z-score versus the sector ETF or market benchmark'),
  ('fld_ABN006', 'field', 'GAP_PCT', 'field_name', 'gap_pct', 'trading-data/storage/templates/data_kinds/events/equity_abnormal_activity_event.preview.csv', 'equity_abnormal_activity_event_template', 'sync_artifact', 'Opening or event-window gap percentage when applicable'),
  ('fld_ABN007', 'field', 'LIQUIDITY_SPREAD_ZSCORE', 'field_name', 'liquidity_spread_zscore', 'trading-data/storage/templates/data_kinds/events/equity_abnormal_activity_event.preview.csv', 'equity_abnormal_activity_event_template', 'sync_artifact', 'Spread/liquidity abnormality z-score from equity quote/liquidity data'),
  ('fld_ABN008', 'field', 'SOURCE_REFS', 'field_name', 'source_refs', 'trading-data/storage/templates/data_kinds/events/equity_abnormal_activity_event.preview.csv', 'equity_abnormal_activity_event_template', 'sync_artifact', 'Compact source references for bars, liquidity windows, sector benchmark, and detection run used for the abnormal activity event')
ON CONFLICT (id) DO UPDATE
SET kind = EXCLUDED.kind,
    key = EXCLUDED.key,
    payload_format = EXCLUDED.payload_format,
    payload = EXCLUDED.payload,
    path = EXCLUDED.path,
    applies_to = EXCLUDED.applies_to,
    artifact_sync_policy = EXCLUDED.artifact_sync_policy,
    note = EXCLUDED.note;
