-- Complete registry coverage for accepted Layer 3 TargetStateVector V1 values.
-- Registers every contract-owned state-vector block/group, model score pattern,
-- derived model payload, and fixed enum/window value that was previously only
-- documented or grouped inside aggregate configs.

UPDATE trading_registry
SET path = 'trading-model/src/models/model_03_target_state_vector/target_state_vector_contract.md',
    applies_to = CASE
      WHEN applies_to LIKE '%sector_state_features%' THEN applies_to
      ELSE COALESCE(applies_to || ';', '') || 'sector_state_features;target_state_vector;model_03_target_state_vector;feature_03_target_state_vector;target_state_vector_model'
    END,
    note = 'Conceptual Layer 2 sector_context_state and Layer 3 sector-state feature group carried inside TargetStateVector rows. It remains direction-neutral sector context and must not become final target/action selection.',
    updated_at = CURRENT_TIMESTAMP
WHERE key = 'SECTOR_CONTEXT_STATE';

INSERT INTO trading_registry (id, kind, key, payload_format, payload, path, applies_to, artifact_sync_policy, note)
VALUES
  ('fld_TSV023', 'field', 'MARKET_REGIME_STATE', 'field_name', 'market_regime_state', 'trading-model/src/models/model_03_target_state_vector/target_state_vector_contract.md', 'market_state_features;target_state_vector;feature_03_target_state_vector;model_03_target_state_vector;target_state_vector_model;model_01_market_regime', 'registry_only', 'TargetStateVector market-state group for current broad market regime/state id or reviewed score bundle inherited from Layer 1.'),
  ('fld_TSV024', 'field', 'MARKET_TREND_STATE', 'field_name', 'market_trend_state', 'trading-model/src/models/model_03_target_state_vector/target_state_vector_contract.md', 'market_state_features;target_state_vector;feature_03_target_state_vector;model_03_target_state_vector;target_state_vector_model;model_01_market_regime', 'registry_only', 'TargetStateVector market-state group for broad trend direction, trend quality, and transition-risk context inherited from Layer 1.'),
  ('fld_TSV025', 'field', 'MARKET_VOLATILITY_STATE', 'field_name', 'market_volatility_state', 'trading-model/src/models/model_03_target_state_vector/target_state_vector_contract.md', 'market_state_features;target_state_vector;feature_03_target_state_vector;model_03_target_state_vector;target_state_vector_model;model_01_market_regime', 'registry_only', 'TargetStateVector market-state group for broad realized/implied/range volatility state where available.'),
  ('fld_TSV026', 'field', 'MARKET_BREADTH_STATE', 'field_name', 'market_breadth_state', 'trading-model/src/models/model_03_target_state_vector/target_state_vector_contract.md', 'market_state_features;target_state_vector;feature_03_target_state_vector;model_03_target_state_vector;target_state_vector_model;model_01_market_regime', 'registry_only', 'TargetStateVector market-state group for broad participation and breadth context when accepted by Layer 1.'),
  ('fld_TSV027', 'field', 'MARKET_LIQUIDITY_STRESS_STATE', 'field_name', 'market_liquidity_stress_state', 'trading-model/src/models/model_03_target_state_vector/target_state_vector_contract.md', 'market_state_features;target_state_vector;feature_03_target_state_vector;model_03_target_state_vector;target_state_vector_model;model_01_market_regime', 'registry_only', 'TargetStateVector market-state group for broad liquidity, stress, and cost context when available.'),
  ('fld_TSV028', 'field', 'MARKET_CORRELATION_STATE', 'field_name', 'market_correlation_state', 'trading-model/src/models/model_03_target_state_vector/target_state_vector_contract.md', 'market_state_features;target_state_vector;feature_03_target_state_vector;model_03_target_state_vector;target_state_vector_model;model_01_market_regime', 'registry_only', 'TargetStateVector market-state group for correlation and risk-on/risk-off background.'),
  ('fld_TSV029', 'field', 'SECTOR_VOLATILITY_STATE', 'field_name', 'sector_volatility_state', 'trading-model/src/models/model_03_target_state_vector/target_state_vector_contract.md', 'sector_state_features;target_state_vector;feature_03_target_state_vector;model_03_target_state_vector;target_state_vector_model;model_02_sector_context', 'registry_only', 'TargetStateVector sector-state group for sector volatility and volatility-vs-market context.'),
  ('fld_TSV030', 'field', 'SECTOR_BREADTH_DISPERSION_STATE', 'field_name', 'sector_breadth_dispersion_state', 'trading-model/src/models/model_03_target_state_vector/target_state_vector_contract.md', 'sector_state_features;target_state_vector;feature_03_target_state_vector;model_03_target_state_vector;target_state_vector_model;model_02_sector_context', 'registry_only', 'TargetStateVector sector-state group for sector internal participation, breadth, and dispersion evidence when available.'),
  ('fld_TSV031', 'field', 'SECTOR_LIQUIDITY_TRADABILITY_STATE', 'field_name', 'sector_liquidity_tradability_state', 'trading-model/src/models/model_03_target_state_vector/target_state_vector_contract.md', 'sector_state_features;target_state_vector;feature_03_target_state_vector;model_03_target_state_vector;target_state_vector_model;model_02_sector_context', 'registry_only', 'TargetStateVector sector-state group for basket liquidity, optionability, and cost context when available.'),
  ('fld_TSV032', 'field', 'TARGET_VOLATILITY_RANGE_STATE', 'field_name', 'target_volatility_range_state', 'trading-model/src/models/model_03_target_state_vector/target_state_vector_contract.md', 'target_state_features;target_state_vector;feature_03_target_state_vector;model_03_target_state_vector;target_state_vector_model', 'registry_only', 'TargetStateVector target-state group for ATR%, realized volatility, intraday range, range location, compression/expansion, and transition-risk pressure.'),
  ('fld_TSV033', 'field', 'TARGET_GAP_JUMP_STATE', 'field_name', 'target_gap_jump_state', 'trading-model/src/models/model_03_target_state_vector/target_state_vector_contract.md', 'target_state_features;target_state_vector;feature_03_target_state_vector;model_03_target_state_vector;target_state_vector_model', 'registry_only', 'TargetStateVector target-state group for opening, overnight, session gap, jump, and abnormal bar movement evidence.'),
  ('fld_TSV034', 'field', 'TARGET_VOLUME_ACTIVITY_STATE', 'field_name', 'target_volume_activity_state', 'trading-model/src/models/model_03_target_state_vector/target_state_vector_contract.md', 'target_state_features;target_state_vector;feature_03_target_state_vector;model_03_target_state_vector;target_state_vector_model', 'registry_only', 'TargetStateVector target-state group for volume, dollar-volume, relative volume, and abnormal activity evidence.'),
  ('fld_TSV035', 'field', 'TARGET_VWAP_LOCATION_STATE', 'field_name', 'target_vwap_location_state', 'trading-model/src/models/model_03_target_state_vector/target_state_vector_contract.md', 'target_state_features;target_state_vector;feature_03_target_state_vector;model_03_target_state_vector;target_state_vector_model', 'registry_only', 'TargetStateVector target-state group for distance from VWAP/session anchors and mean-reversion pressure context.'),
  ('fld_TSV036', 'field', 'TARGET_SESSION_POSITION_STATE', 'field_name', 'target_session_position_state', 'trading-model/src/models/model_03_target_state_vector/target_state_vector_contract.md', 'target_state_features;target_state_vector;feature_03_target_state_vector;model_03_target_state_vector;target_state_vector_model', 'registry_only', 'TargetStateVector target-state group for time-of-day/session-progress context for intraday state interpretation.'),
  ('fld_TSV037', 'field', 'TARGET_DATA_QUALITY_STATE', 'field_name', 'target_data_quality_state', 'trading-model/src/models/model_03_target_state_vector/target_state_vector_contract.md', 'target_state_features;target_state_vector;feature_03_target_state_vector;model_03_target_state_vector;target_state_vector_model', 'registry_only', 'TargetStateVector target-state group for coverage, freshness, missingness, and source-quality diagnostics.'),
  ('fld_TSV038', 'field', 'TARGET_VS_MARKET_VOLATILITY', 'field_name', 'target_vs_market_volatility', 'trading-model/src/models/model_03_target_state_vector/target_state_vector_contract.md', 'cross_state_features;target_state_vector;feature_03_target_state_vector;model_03_target_state_vector;target_state_vector_model', 'registry_only', 'TargetStateVector cross-state group for target volatility/range expansion relative to broad market volatility.'),
  ('fld_TSV039', 'field', 'TARGET_VS_SECTOR_VOLATILITY', 'field_name', 'target_vs_sector_volatility', 'trading-model/src/models/model_03_target_state_vector/target_state_vector_contract.md', 'cross_state_features;target_state_vector;feature_03_target_state_vector;model_03_target_state_vector;target_state_vector_model', 'registry_only', 'TargetStateVector cross-state group for target volatility/range expansion relative to sector volatility.'),
  ('fld_TSV040', 'field', 'TARGET_MARKET_BETA_CORRELATION', 'field_name', 'target_market_beta_correlation', 'trading-model/src/models/model_03_target_state_vector/target_state_vector_contract.md', 'cross_state_features;target_state_vector;feature_03_target_state_vector;model_03_target_state_vector;target_state_vector_model', 'registry_only', 'TargetStateVector cross-state group for rolling beta/correlation to an accepted market reference when enough history exists.'),
  ('fld_TSV041', 'field', 'TARGET_SECTOR_BETA_CORRELATION', 'field_name', 'target_sector_beta_correlation', 'trading-model/src/models/model_03_target_state_vector/target_state_vector_contract.md', 'cross_state_features;target_state_vector;feature_03_target_state_vector;model_03_target_state_vector;target_state_vector_model', 'registry_only', 'TargetStateVector cross-state group for rolling beta/correlation to an accepted sector reference when enough history exists.'),
  ('fld_TSV042', 'field', 'SECTOR_CONFIRMATION_STATE', 'field_name', 'sector_confirmation_state', 'trading-model/src/models/model_03_target_state_vector/target_state_vector_contract.md', 'cross_state_features;target_state_vector;feature_03_target_state_vector;model_03_target_state_vector;target_state_vector_model', 'registry_only', 'TargetStateVector cross-state group describing whether target movement is sector-confirmed, sector-divergent, flat/mixed, or idiosyncratic; keep signed direction alignment separate from support quality.'),
  ('fld_TSV043', 'field', 'IDIOSYNCRATIC_RESIDUAL_STATE', 'field_name', 'idiosyncratic_residual_state', 'trading-model/src/models/model_03_target_state_vector/target_state_vector_contract.md', 'cross_state_features;target_state_vector;feature_03_target_state_vector;model_03_target_state_vector;target_state_vector_model', 'registry_only', 'TargetStateVector cross-state group for residual target movement after market and sector adjustment.'),
  ('fld_TSV044', 'field', 'TARGET_DIRECTION_SCORE_BY_WINDOW', 'field_name', '3_target_direction_score_<window>', 'trading-model/src/models/model_03_target_state_vector/contract.py', 'score_payload;target_state_vector;model_03_target_state_vector;target_state_vector_model;model_evaluation;promotion_evidence', 'registry_only', 'Layer 3 signed current target-state direction score pattern by synchronized state window. Sign is state evidence, not quality, alpha confidence, or position instruction.'),
  ('fld_TSV045', 'field', 'TARGET_TREND_QUALITY_SCORE_BY_WINDOW', 'field_name', '3_target_trend_quality_score_<window>', 'trading-model/src/models/model_03_target_state_vector/contract.py', 'score_payload;target_state_vector;model_03_target_state_vector;target_state_vector_model;model_evaluation;promotion_evidence', 'registry_only', 'Layer 3 direction-neutral target trend clarity/structure score pattern by synchronized state window.'),
  ('fld_TSV046', 'field', 'TARGET_PATH_STABILITY_SCORE_BY_WINDOW', 'field_name', '3_target_path_stability_score_<window>', 'trading-model/src/models/model_03_target_state_vector/contract.py', 'score_payload;target_state_vector;model_03_target_state_vector;target_state_vector_model;model_evaluation;promotion_evidence', 'registry_only', 'Layer 3 direction-neutral target path smoothness/persistence score pattern by synchronized state window.'),
  ('fld_TSV047', 'field', 'TARGET_NOISE_SCORE_BY_WINDOW', 'field_name', '3_target_noise_score_<window>', 'trading-model/src/models/model_03_target_state_vector/contract.py', 'score_payload;target_state_vector;model_03_target_state_vector;target_state_vector_model;model_evaluation;promotion_evidence', 'registry_only', 'Layer 3 target bar-to-bar chop, wick/noise, abnormal jump, and execution-disruptive path-noise score pattern. Higher means worse noise.'),
  ('fld_TSV048', 'field', 'TARGET_TRANSITION_RISK_SCORE_BY_WINDOW', 'field_name', '3_target_transition_risk_score_<window>', 'trading-model/src/models/model_03_target_state_vector/contract.py', 'score_payload;target_state_vector;model_03_target_state_vector;target_state_vector_model;model_evaluation;promotion_evidence', 'registry_only', 'Layer 3 target transition/decay/fragility risk score pattern by synchronized state window. Higher means more risk.'),
  ('fld_TSV049', 'field', 'TARGET_LIQUIDITY_TRADABILITY_SCORE', 'field_name', '3_target_liquidity_tradability_score', 'trading-model/src/models/model_03_target_state_vector/contract.py', 'score_payload;target_state_vector;model_03_target_state_vector;target_state_vector_model;model_evaluation;promotion_evidence', 'registry_only', 'Layer 3 target liquidity, spread, capacity, borrow/shortability, and practical tradability support score.'),
  ('fld_TSV050', 'field', 'CONTEXT_DIRECTION_ALIGNMENT_SCORE_BY_WINDOW', 'field_name', '3_context_direction_alignment_score_<window>', 'trading-model/src/models/model_03_target_state_vector/contract.py', 'score_payload;target_state_vector;model_03_target_state_vector;target_state_vector_model;model_evaluation;promotion_evidence', 'registry_only', 'Layer 3 signed target/sector/market direction-alignment score pattern by synchronized state window.'),
  ('fld_TSV051', 'field', 'CONTEXT_SUPPORT_QUALITY_SCORE_BY_WINDOW', 'field_name', '3_context_support_quality_score_<window>', 'trading-model/src/models/model_03_target_state_vector/contract.py', 'score_payload;target_state_vector;model_03_target_state_vector;target_state_vector_model;model_evaluation;promotion_evidence', 'registry_only', 'Layer 3 direction-neutral market/sector context support-quality score pattern by synchronized state window.'),
  ('fld_TSV052', 'field', 'TARGET_STATE_TRADABILITY_SCORE_BY_WINDOW', 'field_name', '3_tradability_score_<window>', 'trading-model/src/models/model_03_target_state_vector/contract.py', 'score_payload;target_state_vector;model_03_target_state_vector;target_state_vector_model;model_evaluation;promotion_evidence', 'registry_only', 'Layer 3 direction-neutral combined state tradability score pattern by synchronized state window. Stable short states can score highly.'),
  ('fld_TSV053', 'field', 'TARGET_STATE_QUALITY_SCORE', 'field_name', '3_state_quality_score', 'trading-model/src/models/model_03_target_state_vector/contract.py', 'score_payload;target_state_vector;model_03_target_state_vector;target_state_vector_model;model_evaluation;promotion_evidence', 'registry_only', 'Layer 3 reliability/completeness score for the produced target state vector; not opportunity, action, or position size.'),
  ('fld_TSV054', 'field', 'TARGET_STATE_EVIDENCE_COUNT', 'field_name', '3_evidence_count', 'trading-model/src/models/model_03_target_state_vector/contract.py', 'score_payload;target_state_vector;model_03_target_state_vector;target_state_vector_model;model_evaluation;promotion_evidence', 'registry_only', 'Layer 3 count of usable numeric/string evidence fields contributing to the target state-vector row.'),
  ('fld_TSV055', 'field', 'TARGET_STATE_VECTOR_PAYLOAD', 'field_name', 'target_state_vector', 'trading-model/src/models/model_03_target_state_vector/target_state_vector_contract.md', 'target_state_vector;model_03_target_state_vector;target_state_vector_model', 'registry_only', 'Model-facing Layer 3 target state-vector JSON payload containing market_state_features, sector_state_features, target_state_features, cross_state_features, and score_payload.'),
  ('fld_TSV056', 'field', 'TARGET_STATE_SCORE_PAYLOAD', 'field_name', 'score_payload', 'trading-model/src/models/model_03_target_state_vector/target_state_vector_contract.md', 'target_state_vector;model_03_target_state_vector;target_state_vector_model', 'registry_only', 'Layer 3 score payload nested inside target_state_vector and emitted as scalar model-output fields.'),
  ('fld_TSV057', 'field', 'TARGET_STATE_EMBEDDING', 'field_name', 'target_state_embedding', 'trading-model/src/models/model_03_target_state_vector/target_state_vector_contract.md', 'target_state_vector;model_03_target_state_vector;target_state_vector_model', 'registry_only', 'Derived Layer 3 target-state embedding for diagnostics/research; it supports but must not replace the inspectable state-vector blocks.'),
  ('fld_TSV058', 'field', 'STATE_CLUSTER_ID', 'field_name', 'state_cluster_id', 'trading-model/src/models/model_03_target_state_vector/target_state_vector_contract.md', 'target_state_vector;model_03_target_state_vector;target_state_vector_model', 'registry_only', 'Derived Layer 3 target-state cluster id for diagnostics/research; not a downstream action or strategy variant.'),
  ('fld_TSV059', 'field', 'STATE_QUALITY_DIAGNOSTICS', 'field_name', 'state_quality_diagnostics', 'trading-model/src/models/model_03_target_state_vector/target_state_vector_contract.md', 'target_state_vector;model_03_target_state_vector;target_state_vector_model', 'registry_only', 'Layer 3 diagnostics payload for feature quality, window sync, identity leakage checks, downstream-action field checks, and score-field coverage.'),
  ('trm_TSVWIN001', 'term', 'TARGET_STATE_WINDOW_5MIN', 'text', '5min', 'trading-model/src/models/model_03_target_state_vector/target_state_vector_contract.md', 'state_observation_windows;target_state_vector;feature_03_target_state_vector;model_03_target_state_vector;target_state_vector_model', 'registry_only', 'Accepted TargetStateVector synchronized state-observation window value: 5min. This is a state window, not a strategy/action variant.'),
  ('trm_TSVWIN002', 'term', 'TARGET_STATE_WINDOW_15MIN', 'text', '15min', 'trading-model/src/models/model_03_target_state_vector/target_state_vector_contract.md', 'state_observation_windows;target_state_vector;feature_03_target_state_vector;model_03_target_state_vector;target_state_vector_model', 'registry_only', 'Accepted TargetStateVector synchronized state-observation window value: 15min. This is a state window, not a strategy/action variant.'),
  ('trm_TSVWIN003', 'term', 'TARGET_STATE_WINDOW_60MIN', 'text', '60min', 'trading-model/src/models/model_03_target_state_vector/target_state_vector_contract.md', 'state_observation_windows;target_state_vector;feature_03_target_state_vector;model_03_target_state_vector;target_state_vector_model', 'registry_only', 'Accepted TargetStateVector synchronized state-observation window value: 60min. This is a state window, not a strategy/action variant.'),
  ('trm_TSVWIN004', 'term', 'TARGET_STATE_WINDOW_390MIN', 'text', '390min', 'trading-model/src/models/model_03_target_state_vector/target_state_vector_contract.md', 'state_observation_windows;target_state_vector;feature_03_target_state_vector;model_03_target_state_vector;target_state_vector_model', 'registry_only', 'Accepted TargetStateVector synchronized state-observation window value: 390min. This is a state window, not a strategy/action variant.'),
  ('trm_TSVSC001', 'term', 'SECTOR_CONFIRMATION_STATE_CONFIRMED', 'text', 'sector_confirmed', 'trading-model/src/models/model_03_target_state_vector/target_state_vector_contract.md', 'sector_confirmation_state;cross_state_features;target_state_vector;target_state_vector_model', 'registry_only', 'Sector confirmation value: target movement is directionally confirmed by sector context.'),
  ('trm_TSVSC002', 'term', 'SECTOR_CONFIRMATION_STATE_DIVERGENT', 'text', 'sector_divergent', 'trading-model/src/models/model_03_target_state_vector/target_state_vector_contract.md', 'sector_confirmation_state;cross_state_features;target_state_vector;target_state_vector_model', 'registry_only', 'Sector confirmation value: target movement diverges from sector context.'),
  ('trm_TSVSC003', 'term', 'SECTOR_CONFIRMATION_STATE_FLAT_OR_MIXED', 'text', 'flat_or_mixed', 'trading-model/src/models/model_03_target_state_vector/target_state_vector_contract.md', 'sector_confirmation_state;cross_state_features;target_state_vector;target_state_vector_model', 'registry_only', 'Sector confirmation value: target and/or sector movement is flat, mixed, or unresolved.'),
  ('trm_TSVWP001', 'term', 'TARGET_SESSION_WINDOW_POLICY_COMPLETED_1MIN_BARS', 'text', 'completed_1min_bars', 'trading-model/src/models/model_03_target_state_vector/target_state_vector_contract.md', 'target_session_position_state;target_state_features;feature_03_target_state_vector;target_state_vector_model', 'registry_only', 'Layer 3 target session-position window-policy value used by the deterministic feature scaffold: completed one-minute bars only.')
ON CONFLICT (id) DO UPDATE SET
    kind = EXCLUDED.kind,
    key = EXCLUDED.key,
    payload_format = EXCLUDED.payload_format,
    payload = EXCLUDED.payload,
    path = EXCLUDED.path,
    applies_to = EXCLUDED.applies_to,
    artifact_sync_policy = EXCLUDED.artifact_sync_policy,
    note = EXCLUDED.note,
    updated_at = CURRENT_TIMESTAMP;
