-- Register anonymous target candidate builder output fields and shared values.
-- These names are emitted by the Layer 3 candidate-preparation scaffold and are
-- consumed as point-in-time TargetStateVectorModel preprocessing evidence.

INSERT INTO trading_registry (id, kind, key, payload_format, payload, path, applies_to, artifact_sync_policy, note)
VALUES
  ('fld_ATC001', 'field', 'CANDIDATE_BUILDER_VERSION', 'field_name', 'candidate_builder_version', 'trading-model/src/models/model_03_target_state_vector/anonymous_target_candidate_builder/target_candidate_builder_contract.md', 'anonymous_target_candidate_builder;anonymous_target_feature_vector;model_03_target_state_vector;target_state_vector_model', 'registry_only', 'Version/config label for the Layer 3 anonymous target candidate builder that produced the candidate row.'),
  ('fld_ATC002', 'field', 'CANDIDATE_ELIGIBILITY_STATE', 'field_name', 'candidate_eligibility_state', 'trading-model/src/models/model_03_target_state_vector/anonymous_target_candidate_builder/target_candidate_builder_contract.md', 'anonymous_target_candidate_builder;anonymous_target_feature_vector;model_03_target_state_vector;target_state_vector_model', 'registry_only', 'Layer 3 candidate-preparation eligibility state. This gates whether a candidate can flow into target-state vector generation; it is not an action or trade instruction.'),
  ('fld_ATC003', 'field', 'CANDIDATE_SOURCE_RANK', 'field_name', 'candidate_source_rank', 'trading-model/src/models/model_03_target_state_vector/anonymous_target_candidate_builder/target_candidate_builder_contract.md', 'anonymous_target_candidate_builder;anonymous_target_feature_vector;model_03_target_state_vector;target_state_vector_model', 'registry_only', 'Rank inherited from Layer 2 sector/basket transmission or target evidence during anonymous candidate preparation; not a portfolio weight.'),
  ('fld_ATC004', 'field', 'CANDIDATE_GENERATION_REASON_CODES', 'field_name', 'candidate_generation_reason_codes', 'trading-model/src/models/model_03_target_state_vector/anonymous_target_candidate_builder/target_candidate_builder_contract.md', 'anonymous_target_candidate_builder;anonymous_target_feature_vector;model_03_target_state_vector;target_state_vector_model', 'registry_only', 'Semicolon-delimited reason-code field explaining why the anonymous target candidate row was generated, watched, excluded, or quality-gated.'),
  ('fld_ATC005', 'field', 'CANDIDATE_DATA_QUALITY_SCORE', 'field_name', 'candidate_data_quality_score', 'trading-model/src/models/model_03_target_state_vector/anonymous_target_candidate_builder/target_candidate_builder_contract.md', 'anonymous_target_candidate_builder;anonymous_target_feature_vector;model_03_target_state_vector;target_state_vector_model;target_state_vector', 'registry_only', 'Coverage/freshness/reliability summary for anonymous target candidate preparation evidence; describes row reliability, not opportunity or position sizing.'),
  ('fld_ATC006', 'field', 'CANDIDATE_ANONYMITY_CHECK_STATE', 'field_name', 'candidate_anonymity_check_state', 'trading-model/src/models/model_03_target_state_vector/anonymous_target_candidate_builder/target_candidate_builder_contract.md', 'anonymous_target_candidate_builder;anonymous_target_feature_vector;model_03_target_state_vector;target_state_vector_model', 'registry_only', 'Pass/watch/fail state for candidate identity-leakage checks; raw ticker/company identity must remain outside model-facing vectors.'),
  ('trm_ATCEL001', 'term', 'CANDIDATE_ELIGIBILITY_ELIGIBLE', 'text', 'eligible', 'trading-model/src/models/model_03_target_state_vector/anonymous_target_candidate_builder/target_candidate_builder_contract.md', 'candidate_eligibility_state;anonymous_target_candidate_builder;target_state_vector_model', 'registry_only', 'Candidate eligibility value: candidate has enough point-in-time evidence to flow downstream.'),
  ('trm_ATCEL002', 'term', 'CANDIDATE_ELIGIBILITY_WATCH', 'text', 'watch', 'trading-model/src/models/model_03_target_state_vector/anonymous_target_candidate_builder/target_candidate_builder_contract.md', 'candidate_eligibility_state;anonymous_target_candidate_builder;target_state_vector_model', 'registry_only', 'Candidate eligibility value: candidate may be retained for observation but needs caution or additional review/evidence.'),
  ('trm_ATCEL003', 'term', 'CANDIDATE_ELIGIBILITY_EXCLUDED', 'text', 'excluded', 'trading-model/src/models/model_03_target_state_vector/anonymous_target_candidate_builder/target_candidate_builder_contract.md', 'candidate_eligibility_state;anonymous_target_candidate_builder;target_state_vector_model', 'registry_only', 'Candidate eligibility value: candidate is blocked from downstream target-state vector generation.'),
  ('trm_ATCEL004', 'term', 'CANDIDATE_ELIGIBILITY_INSUFFICIENT_DATA', 'text', 'insufficient_data', 'trading-model/src/models/model_03_target_state_vector/anonymous_target_candidate_builder/target_candidate_builder_contract.md', 'candidate_eligibility_state;anonymous_target_candidate_builder;target_state_vector_model', 'registry_only', 'Candidate eligibility value: available point-in-time evidence is not sufficient for candidate construction.'),
  ('trm_ATCAN001', 'term', 'CANDIDATE_ANONYMITY_PASS', 'text', 'pass', 'trading-model/src/models/model_03_target_state_vector/anonymous_target_candidate_builder/target_candidate_builder_contract.md', 'candidate_anonymity_check_state;anonymous_target_candidate_builder;target_state_vector_model', 'registry_only', 'Candidate anonymity check value: no registered identity-leakage issue was detected.'),
  ('trm_ATCAN002', 'term', 'CANDIDATE_ANONYMITY_WATCH', 'text', 'watch', 'trading-model/src/models/model_03_target_state_vector/anonymous_target_candidate_builder/target_candidate_builder_contract.md', 'candidate_anonymity_check_state;anonymous_target_candidate_builder;target_state_vector_model', 'registry_only', 'Candidate anonymity check value: structural bucket combinations or evidence patterns require caution before promotion.'),
  ('trm_ATCAN003', 'term', 'CANDIDATE_ANONYMITY_FAIL', 'text', 'fail', 'trading-model/src/models/model_03_target_state_vector/anonymous_target_candidate_builder/target_candidate_builder_contract.md', 'candidate_anonymity_check_state;anonymous_target_candidate_builder;target_state_vector_model', 'registry_only', 'Candidate anonymity check value: identity-leakage checks failed and the candidate must be excluded from fitting vectors.'),
  ('trm_ATCRC001', 'term', 'CANDIDATE_REASON_LAYER2_SECTOR_TRANSMISSION', 'text', '3_LAYER2_SECTOR_TRANSMISSION', 'trading-model/src/models/model_03_target_state_vector/anonymous_target_candidate_builder/builder.py', 'candidate_generation_reason_codes;anonymous_target_candidate_builder;target_state_vector_model', 'registry_only', 'Anonymous target candidate reason code: candidate originated from accepted Layer 2 sector/basket transmission.'),
  ('trm_ATCRC002', 'term', 'CANDIDATE_REASON_TARGET_LOCAL_EVIDENCE_JOINED', 'text', '3_TARGET_LOCAL_EVIDENCE_JOINED', 'trading-model/src/models/model_03_target_state_vector/anonymous_target_candidate_builder/builder.py', 'candidate_generation_reason_codes;anonymous_target_candidate_builder;target_state_vector_model', 'registry_only', 'Anonymous target candidate reason code: target-local evidence was joined to the candidate row.'),
  ('trm_ATCRC003', 'term', 'CANDIDATE_REASON_LAYER2_SECTOR_NOT_SELECTED_OR_WATCH', 'text', '3_LAYER2_SECTOR_NOT_SELECTED_OR_WATCH', 'trading-model/src/models/model_03_target_state_vector/anonymous_target_candidate_builder/builder.py', 'candidate_generation_reason_codes;anonymous_target_candidate_builder;target_state_vector_model', 'registry_only', 'Anonymous target candidate reason code: upstream Layer 2 sector state was not selected/watch and candidate was excluded.'),
  ('trm_ATCRC004', 'term', 'CANDIDATE_REASON_MISSING_EXPOSURE_TRANSMISSION', 'text', '3_MISSING_EXPOSURE_TRANSMISSION', 'trading-model/src/models/model_03_target_state_vector/anonymous_target_candidate_builder/builder.py', 'candidate_generation_reason_codes;anonymous_target_candidate_builder;target_state_vector_model', 'registry_only', 'Anonymous target candidate reason code: required exposure transmission evidence was missing.'),
  ('trm_ATCRC005', 'term', 'CANDIDATE_REASON_LOW_EVIDENCE_COVERAGE', 'text', '3_LOW_CANDIDATE_EVIDENCE_COVERAGE', 'trading-model/src/models/model_03_target_state_vector/anonymous_target_candidate_builder/builder.py', 'candidate_generation_reason_codes;anonymous_target_candidate_builder;target_state_vector_model', 'registry_only', 'Anonymous target candidate reason code: available evidence coverage was below candidate-preparation requirements.'),
  ('trm_ATCRC006', 'term', 'CANDIDATE_REASON_WIDE_SPREAD_WATCH', 'text', '3_WIDE_SPREAD_WATCH', 'trading-model/src/models/model_03_target_state_vector/anonymous_target_candidate_builder/builder.py', 'candidate_generation_reason_codes;anonymous_target_candidate_builder;target_state_vector_model', 'registry_only', 'Anonymous target candidate reason code: spread/cost evidence puts the candidate into watch state.'),
  ('trm_ATCRC007', 'term', 'CANDIDATE_REASON_LAYER2_TRANSMISSION_TARGET_CANDIDATE', 'text', '3_LAYER2_TRANSMISSION_TARGET_CANDIDATE', 'trading-model/src/models/model_03_target_state_vector/anonymous_target_candidate_builder/builder.py', 'candidate_generation_reason_codes;anonymous_target_candidate_builder;target_state_vector_model', 'registry_only', 'Anonymous target candidate reason code: normal candidate produced from Layer 2 transmission and target evidence.'),
  ('trm_ATCRC008', 'term', 'CANDIDATE_REASON_INSUFFICIENT_TARGET_EVIDENCE', 'text', '3_INSUFFICIENT_TARGET_EVIDENCE', 'trading-model/src/models/model_03_target_state_vector/anonymous_target_candidate_builder/builder.py', 'candidate_generation_reason_codes;anonymous_target_candidate_builder;target_state_vector_model', 'registry_only', 'Anonymous target candidate reason code: target-local evidence was insufficient.'),
  ('trm_ATCRC009', 'term', 'CANDIDATE_REASON_ANONYMITY_BUCKET_WATCH', 'text', '3_ANONYMITY_BUCKET_WATCH', 'trading-model/src/models/model_03_target_state_vector/anonymous_target_candidate_builder/builder.py', 'candidate_generation_reason_codes;anonymous_target_candidate_builder;target_state_vector_model', 'registry_only', 'Anonymous target candidate reason code: anonymity bucket combination requires watch-state handling.'),
  ('trm_ATCRC010', 'term', 'CANDIDATE_REASON_ANONYMITY_CHECK_FAILED', 'text', '3_ANONYMITY_CHECK_FAILED', 'trading-model/src/models/model_03_target_state_vector/anonymous_target_candidate_builder/builder.py', 'candidate_generation_reason_codes;anonymous_target_candidate_builder;target_state_vector_model', 'registry_only', 'Anonymous target candidate reason code: identity-leakage/anonymity checks failed.'),
  ('trm_ATCRC011', 'term', 'CANDIDATE_REASON_DUPLICATE_CANDIDATE_COLLAPSED', 'text', '3_DUPLICATE_CANDIDATE_COLLAPSED', 'trading-model/src/models/model_03_target_state_vector/anonymous_target_candidate_builder/builder.py', 'candidate_generation_reason_codes;anonymous_target_candidate_builder;target_state_vector_model', 'registry_only', 'Anonymous target candidate reason code: duplicate candidate rows were collapsed during candidate preparation.')
ON CONFLICT (id) DO UPDATE SET
    kind = EXCLUDED.kind,
    key = EXCLUDED.key,
    payload_format = EXCLUDED.payload_format,
    payload = EXCLUDED.payload,
    path = EXCLUDED.path,
    applies_to = EXCLUDED.applies_to,
    artifact_sync_policy = EXCLUDED.artifact_sync_policy,
    note = EXCLUDED.note,
    updated_at = CURRENT_TIMESTAMP;
