-- Prefix all state_vector_value registry keys and payload tokens with their owning model layer.
-- State-vector semantic values are layer-owned contract tokens; avoid bare
-- names inside kind=state_vector_value so rows remain unambiguous across models.

WITH scope_updates(id, new_applies_to) AS (
  VALUES
    ('fld_TSV050', '3_score_payload;3_target_state_vector;model_03_target_state_vector;target_state_vector_model;model_evaluation;promotion_evidence'),
    ('fld_TSV051', '3_score_payload;3_target_state_vector;model_03_target_state_vector;target_state_vector_model;model_evaluation;promotion_evidence'),
    ('fld_TSV043', '3_cross_state_features;3_target_state_vector;feature_03_target_state_vector;model_03_target_state_vector;target_state_vector_model'),
    ('fld_TSV026', '3_market_state_features;3_target_state_vector;feature_03_target_state_vector;model_03_target_state_vector;target_state_vector_model;model_01_market_regime'),
    ('fld_TSV028', '3_market_state_features;3_target_state_vector;feature_03_target_state_vector;model_03_target_state_vector;target_state_vector_model;model_01_market_regime'),
    ('fld_TSV027', '3_market_state_features;3_target_state_vector;feature_03_target_state_vector;model_03_target_state_vector;target_state_vector_model;model_01_market_regime'),
    ('fld_TSV023', '3_market_state_features;3_target_state_vector;feature_03_target_state_vector;model_03_target_state_vector;target_state_vector_model;model_01_market_regime'),
    ('fld_TSV024', '3_market_state_features;3_target_state_vector;feature_03_target_state_vector;model_03_target_state_vector;target_state_vector_model;model_01_market_regime'),
    ('fld_TSV025', '3_market_state_features;3_target_state_vector;feature_03_target_state_vector;model_03_target_state_vector;target_state_vector_model;model_01_market_regime'),
    ('fld_TSV022', '3_cross_state_features;feature_03_target_state_vector;model_03_target_state_vector;target_state_vector_model'),
    ('fld_TSV030', '3_sector_state_features;3_target_state_vector;feature_03_target_state_vector;model_03_target_state_vector;target_state_vector_model;model_02_sector_context'),
    ('fld_TSV042', '3_cross_state_features;3_target_state_vector;feature_03_target_state_vector;model_03_target_state_vector;target_state_vector_model'),
    ('trm_TSVSC001', '3_sector_confirmation_state;3_cross_state_features;3_target_state_vector;target_state_vector_model'),
    ('trm_TSVSC002', '3_sector_confirmation_state;3_cross_state_features;3_target_state_vector;target_state_vector_model'),
    ('trm_TSVSC003', '3_sector_confirmation_state;3_cross_state_features;3_target_state_vector;target_state_vector_model'),
    ('fld_TSV031', '3_sector_state_features;3_target_state_vector;feature_03_target_state_vector;model_03_target_state_vector;target_state_vector_model;model_02_sector_context'),
    ('fld_TSV015', '3_sector_state_features;feature_03_target_state_vector;model_03_target_state_vector;target_state_vector_model;model_02_sector_context'),
    ('fld_TSV016', '3_sector_state_features;feature_03_target_state_vector;model_03_target_state_vector;target_state_vector_model;model_02_sector_context'),
    ('fld_TSV029', '3_sector_state_features;3_target_state_vector;feature_03_target_state_vector;model_03_target_state_vector;target_state_vector_model;model_02_sector_context'),
    ('fld_TSV058', '3_target_state_vector;model_03_target_state_vector;target_state_vector_model'),
    ('fld_TSV011', 'model_03_target_state_vector;feature_03_target_state_vector;target_state_vector_model;3_market_state_features;3_sector_state_features;3_target_state_features;3_cross_state_features'),
    ('fld_TSV059', '3_target_state_vector;model_03_target_state_vector;target_state_vector_model'),
    ('fld_TSV012', 'model_03_target_state_vector;feature_03_target_state_vector;target_state_vector_model;3_market_state_features;3_sector_state_features;3_target_state_features;3_cross_state_features'),
    ('fld_TSV037', '3_target_state_features;3_target_state_vector;feature_03_target_state_vector;model_03_target_state_vector;target_state_vector_model'),
    ('fld_TSV017', '3_target_state_features;feature_03_target_state_vector;model_03_target_state_vector;target_state_vector_model'),
    ('fld_TSV044', '3_score_payload;3_target_state_vector;model_03_target_state_vector;target_state_vector_model;model_evaluation;promotion_evidence'),
    ('fld_TSV033', '3_target_state_features;3_target_state_vector;feature_03_target_state_vector;model_03_target_state_vector;target_state_vector_model'),
    ('fld_TSV049', '3_score_payload;3_target_state_vector;model_03_target_state_vector;target_state_vector_model;model_evaluation;promotion_evidence'),
    ('fld_TSV019', '3_target_state_features;feature_03_target_state_vector;model_03_target_state_vector;target_state_vector_model'),
    ('fld_TSV040', '3_cross_state_features;3_target_state_vector;feature_03_target_state_vector;model_03_target_state_vector;target_state_vector_model'),
    ('fld_TSV047', '3_score_payload;3_target_state_vector;model_03_target_state_vector;target_state_vector_model;model_evaluation;promotion_evidence'),
    ('fld_TSV046', '3_score_payload;3_target_state_vector;model_03_target_state_vector;target_state_vector_model;model_evaluation;promotion_evidence'),
    ('fld_TSV041', '3_cross_state_features;3_target_state_vector;feature_03_target_state_vector;model_03_target_state_vector;target_state_vector_model'),
    ('fld_TSV036', '3_target_state_features;3_target_state_vector;feature_03_target_state_vector;model_03_target_state_vector;target_state_vector_model'),
    ('trm_TSVWP001', '3_target_session_position_state;3_target_state_features;feature_03_target_state_vector;target_state_vector_model'),
    ('fld_TSV057', '3_target_state_vector;model_03_target_state_vector;target_state_vector_model'),
    ('fld_TSV054', '3_score_payload;3_target_state_vector;model_03_target_state_vector;target_state_vector_model;model_evaluation;promotion_evidence'),
    ('fld_TSV053', '3_score_payload;3_target_state_vector;model_03_target_state_vector;target_state_vector_model;model_evaluation;promotion_evidence'),
    ('fld_TSV056', '3_target_state_vector;model_03_target_state_vector;target_state_vector_model'),
    ('fld_TSV052', '3_score_payload;3_target_state_vector;model_03_target_state_vector;target_state_vector_model;model_evaluation;promotion_evidence'),
    ('fld_TSV055', '3_target_state_vector;model_03_target_state_vector;target_state_vector_model'),
    ('trm_TSVWIN002', '3_state_observation_windows;3_target_state_vector;feature_03_target_state_vector;model_03_target_state_vector;target_state_vector_model'),
    ('trm_TSVWIN004', '3_state_observation_windows;3_target_state_vector;feature_03_target_state_vector;model_03_target_state_vector;target_state_vector_model'),
    ('trm_TSVWIN001', '3_state_observation_windows;3_target_state_vector;feature_03_target_state_vector;model_03_target_state_vector;target_state_vector_model'),
    ('trm_TSVWIN003', '3_state_observation_windows;3_target_state_vector;feature_03_target_state_vector;model_03_target_state_vector;target_state_vector_model'),
    ('fld_TSV048', '3_score_payload;3_target_state_vector;model_03_target_state_vector;target_state_vector_model;model_evaluation;promotion_evidence'),
    ('fld_TSV045', '3_score_payload;3_target_state_vector;model_03_target_state_vector;target_state_vector_model;model_evaluation;promotion_evidence'),
    ('fld_TSV018', '3_target_state_features;feature_03_target_state_vector;model_03_target_state_vector;target_state_vector_model'),
    ('fld_TSV032', '3_target_state_features;3_target_state_vector;feature_03_target_state_vector;model_03_target_state_vector;target_state_vector_model'),
    ('fld_TSV034', '3_target_state_features;3_target_state_vector;feature_03_target_state_vector;model_03_target_state_vector;target_state_vector_model'),
    ('fld_TSV020', '3_cross_state_features;feature_03_target_state_vector;model_03_target_state_vector;target_state_vector_model'),
    ('fld_TSV038', '3_cross_state_features;3_target_state_vector;feature_03_target_state_vector;model_03_target_state_vector;target_state_vector_model'),
    ('fld_TSV021', '3_cross_state_features;feature_03_target_state_vector;model_03_target_state_vector;target_state_vector_model'),
    ('fld_TSV039', '3_cross_state_features;3_target_state_vector;feature_03_target_state_vector;model_03_target_state_vector;target_state_vector_model'),
    ('fld_TSV035', '3_target_state_features;3_target_state_vector;feature_03_target_state_vector;model_03_target_state_vector;target_state_vector_model')
)
UPDATE trading_registry r
SET applies_to = scope_updates.new_applies_to,
    updated_at = CURRENT_TIMESTAMP
FROM scope_updates
WHERE r.id = scope_updates.id
  AND r.kind = 'state_vector_value'
  AND r.applies_to IS DISTINCT FROM scope_updates.new_applies_to;

WITH value_updates(id, new_key, new_payload) AS (
  VALUES
    ('fld_MRMV22007', 'MODEL_01_BREADTH_PARTICIPATION_SCORE_VALUE', '1_breadth_participation_score'),
    ('fld_TSV050', 'MODEL_03_CONTEXT_DIRECTION_ALIGNMENT_SCORE_BY_WINDOW_VALUE', '3_context_direction_alignment_score_<window>'),
    ('fld_TSV051', 'MODEL_03_CONTEXT_SUPPORT_QUALITY_SCORE_BY_WINDOW_VALUE', '3_context_support_quality_score_<window>'),
    ('fld_MRMV22008', 'MODEL_01_CORRELATION_CROWDING_SCORE_VALUE', '1_correlation_crowding_score'),
    ('fld_TSV010', 'MODEL_03_CROSS_STATE_FEATURES_VALUE', '3_cross_state_features'),
    ('fld_MRMV22009', 'MODEL_01_DISPERSION_OPPORTUNITY_SCORE_VALUE', '1_dispersion_opportunity_score'),
    ('fld_TSV013', 'MODEL_03_FEATURE_QUALITY_DIAGNOSTICS_VALUE', '3_feature_quality_diagnostics'),
    ('fld_TSV043', 'MODEL_03_IDIOSYNCRATIC_RESIDUAL_STATE_VALUE', '3_idiosyncratic_residual_state'),
    ('fld_TSV026', 'MODEL_03_MARKET_BREADTH_STATE_VALUE', '3_market_breadth_state'),
    ('fld_SCMV22005', 'MODEL_02_MARKET_CONTEXT_SUPPORT_SCORE_VALUE', '2_market_context_support_score'),
    ('fld_TSV028', 'MODEL_03_MARKET_CORRELATION_STATE_VALUE', '3_market_correlation_state'),
    ('fld_MRMV22012', 'MODEL_01_MARKET_COVERAGE_SCORE_VALUE', '1_coverage_score'),
    ('fld_MRMV22013', 'MODEL_01_MARKET_DATA_QUALITY_SCORE_VALUE', '1_data_quality_score'),
    ('fld_MRMV22001', 'MODEL_01_MARKET_DIRECTION_SCORE_VALUE', '1_market_direction_score'),
    ('fld_MRMV22002', 'MODEL_01_MARKET_DIRECTION_STRENGTH_SCORE_VALUE', '1_market_direction_strength_score'),
    ('fld_MRMV22010', 'MODEL_01_MARKET_LIQUIDITY_PRESSURE_SCORE_VALUE', '1_market_liquidity_pressure_score'),
    ('fld_TSV027', 'MODEL_03_MARKET_LIQUIDITY_STRESS_STATE_VALUE', '3_market_liquidity_stress_state'),
    ('fld_MRMV22011', 'MODEL_01_MARKET_LIQUIDITY_SUPPORT_SCORE_VALUE', '1_market_liquidity_support_score'),
    ('fld_TSV023', 'MODEL_03_MARKET_REGIME_STATE_VALUE', '3_market_regime_state'),
    ('fld_MRMV22005', 'MODEL_01_MARKET_RISK_STRESS_SCORE_VALUE', '1_market_risk_stress_score'),
    ('fld_MRMV22004', 'MODEL_01_MARKET_STABILITY_SCORE_VALUE', '1_market_stability_score'),
    ('fld_TSV007', 'MODEL_03_MARKET_STATE_FEATURES_VALUE', '3_market_state_features'),
    ('fld_MRMV22006', 'MODEL_01_MARKET_TRANSITION_RISK_SCORE_VALUE', '1_market_transition_risk_score'),
    ('fld_MRMV22003', 'MODEL_01_MARKET_TREND_QUALITY_SCORE_VALUE', '1_market_trend_quality_score'),
    ('fld_TSV024', 'MODEL_03_MARKET_TREND_STATE_VALUE', '3_market_trend_state'),
    ('fld_TSV025', 'MODEL_03_MARKET_VOLATILITY_STATE_VALUE', '3_market_volatility_state'),
    ('fld_TSV022', 'MODEL_03_RELATIVE_LIQUIDITY_TRADABILITY_STATE_VALUE', '3_relative_liquidity_tradability_state'),
    ('fld_SCMV22006', 'MODEL_02_SECTOR_BREADTH_CONFIRMATION_SCORE_VALUE', '2_sector_breadth_confirmation_score'),
    ('fld_TSV030', 'MODEL_03_SECTOR_BREADTH_DISPERSION_STATE_VALUE', '3_sector_breadth_dispersion_state'),
    ('fld_TSV042', 'MODEL_03_SECTOR_CONFIRMATION_STATE_VALUE', '3_sector_confirmation_state'),
    ('trm_TSVSC001', 'MODEL_03_SECTOR_CONFIRMATION_STATE_CONFIRMED_VALUE', '3_sector_confirmation_state_sector_confirmed'),
    ('trm_TSVSC002', 'MODEL_03_SECTOR_CONFIRMATION_STATE_DIVERGENT_VALUE', '3_sector_confirmation_state_sector_divergent'),
    ('trm_TSVSC003', 'MODEL_03_SECTOR_CONFIRMATION_STATE_FLAT_OR_MIXED_VALUE', '3_sector_confirmation_state_flat_or_mixed'),
    ('fld_SCMV22017', 'MODEL_02_SECTOR_COVERAGE_SCORE_VALUE', '2_coverage_score'),
    ('fld_SCMV22018', 'MODEL_02_SECTOR_DATA_QUALITY_SCORE_VALUE', '2_data_quality_score'),
    ('fld_SCMV22007', 'MODEL_02_SECTOR_DISPERSION_CROWDING_SCORE_VALUE', '2_sector_dispersion_crowding_score'),
    ('fld_SCMV22015', 'MODEL_02_SECTOR_ELIGIBILITY_REASON_CODES_VALUE', '2_eligibility_reason_codes'),
    ('fld_SCMV22014', 'MODEL_02_SECTOR_ELIGIBILITY_STATE_VALUE', '2_eligibility_state'),
    ('svv_SCME001', 'MODEL_02_SECTOR_ELIGIBILITY_STATE_ELIGIBLE_VALUE', '2_sector_eligibility_state_eligible'),
    ('svv_SCME003', 'MODEL_02_SECTOR_ELIGIBILITY_STATE_EXCLUDED_VALUE', '2_sector_eligibility_state_excluded'),
    ('svv_SCME004', 'MODEL_02_SECTOR_ELIGIBILITY_STATE_INSUFFICIENT_DATA_VALUE', '2_sector_eligibility_state_insufficient_data'),
    ('svv_SCME002', 'MODEL_02_SECTOR_ELIGIBILITY_STATE_WATCH_VALUE', '2_sector_eligibility_state_watch'),
    ('fld_SCMV22019', 'MODEL_02_SECTOR_EVIDENCE_COUNT_VALUE', '2_evidence_count'),
    ('fld_SCMV22011', 'MODEL_02_SECTOR_HANDOFF_BIAS_VALUE', '2_sector_handoff_bias'),
    ('trm_SCMB001', 'MODEL_02_SECTOR_HANDOFF_BIAS_LONG_BIAS_VALUE', '2_sector_handoff_bias_long_bias'),
    ('trm_SCMB004', 'MODEL_02_SECTOR_HANDOFF_BIAS_MIXED_VALUE', '2_sector_handoff_bias_mixed'),
    ('trm_SCMB003', 'MODEL_02_SECTOR_HANDOFF_BIAS_NEUTRAL_VALUE', '2_sector_handoff_bias_neutral'),
    ('trm_SCMB002', 'MODEL_02_SECTOR_HANDOFF_BIAS_SHORT_BIAS_VALUE', '2_sector_handoff_bias_short_bias'),
    ('fld_SCMV22012', 'MODEL_02_SECTOR_HANDOFF_RANK_VALUE', '2_sector_handoff_rank'),
    ('fld_SCMV22013', 'MODEL_02_SECTOR_HANDOFF_REASON_CODES_VALUE', '2_sector_handoff_reason_codes'),
    ('fld_SCMV22010', 'MODEL_02_SECTOR_HANDOFF_STATE_VALUE', '2_sector_handoff_state'),
    ('trm_SCMHS003', 'MODEL_02_SECTOR_HANDOFF_STATE_BLOCKED_VALUE', '2_sector_handoff_state_blocked'),
    ('trm_SCMHS004', 'MODEL_02_SECTOR_HANDOFF_STATE_INSUFFICIENT_DATA_VALUE', '2_sector_handoff_state_insufficient_data'),
    ('trm_SCMHS001', 'MODEL_02_SECTOR_HANDOFF_STATE_SELECTED_VALUE', '2_sector_handoff_state_selected'),
    ('trm_SCMHS002', 'MODEL_02_SECTOR_HANDOFF_STATE_WATCH_VALUE', '2_sector_handoff_state_watch'),
    ('fld_SCMV22008', 'MODEL_02_SECTOR_LIQUIDITY_TRADABILITY_SCORE_VALUE', '2_sector_liquidity_tradability_score'),
    ('fld_TSV031', 'MODEL_03_SECTOR_LIQUIDITY_TRADABILITY_STATE_VALUE', '3_sector_liquidity_tradability_state'),
    ('fld_SCMV22001', 'MODEL_02_SECTOR_RELATIVE_DIRECTION_SCORE_VALUE', '2_sector_relative_direction_score'),
    ('fld_TSV015', 'MODEL_03_SECTOR_RELATIVE_DIRECTION_STATE_VALUE', '3_sector_relative_direction_state'),
    ('fld_TSV008', 'MODEL_03_SECTOR_STATE_FEATURES_VALUE', '3_sector_state_features'),
    ('fld_SCMV22016', 'MODEL_02_SECTOR_STATE_QUALITY_SCORE_VALUE', '2_state_quality_score'),
    ('fld_SCMV22009', 'MODEL_02_SECTOR_TRADABILITY_SCORE_VALUE', '2_sector_tradability_score'),
    ('fld_SCMV22004', 'MODEL_02_SECTOR_TRANSITION_RISK_SCORE_VALUE', '2_sector_transition_risk_score'),
    ('fld_SCMV22002', 'MODEL_02_SECTOR_TREND_QUALITY_SCORE_VALUE', '2_sector_trend_quality_score'),
    ('fld_TSV016', 'MODEL_03_SECTOR_TREND_QUALITY_STABILITY_STATE_VALUE', '3_sector_trend_quality_stability_state'),
    ('fld_SCMV22003', 'MODEL_02_SECTOR_TREND_STABILITY_SCORE_VALUE', '2_sector_trend_stability_score'),
    ('fld_TSV029', 'MODEL_03_SECTOR_VOLATILITY_STATE_VALUE', '3_sector_volatility_state'),
    ('fld_TSV058', 'MODEL_03_STATE_CLUSTER_ID_VALUE', '3_state_cluster_id'),
    ('fld_TSV011', 'MODEL_03_STATE_OBSERVATION_WINDOWS_VALUE', '3_state_observation_windows'),
    ('fld_TSV059', 'MODEL_03_STATE_QUALITY_DIAGNOSTICS_VALUE', '3_state_quality_diagnostics'),
    ('fld_TSV012', 'MODEL_03_STATE_WINDOW_SYNC_POLICY_VALUE', '3_state_window_sync_policy'),
    ('fld_TSV037', 'MODEL_03_TARGET_DATA_QUALITY_STATE_VALUE', '3_target_data_quality_state'),
    ('fld_TSV017', 'MODEL_03_TARGET_DIRECTION_RETURN_SHAPE_VALUE', '3_target_direction_return_shape'),
    ('fld_TSV044', 'MODEL_03_TARGET_DIRECTION_SCORE_BY_WINDOW_VALUE', '3_target_direction_score_<window>'),
    ('fld_TSV033', 'MODEL_03_TARGET_GAP_JUMP_STATE_VALUE', '3_target_gap_jump_state'),
    ('fld_TSV049', 'MODEL_03_TARGET_LIQUIDITY_TRADABILITY_SCORE_VALUE', '3_target_liquidity_tradability_score'),
    ('fld_TSV019', 'MODEL_03_TARGET_LIQUIDITY_TRADABILITY_STATE_VALUE', '3_target_liquidity_tradability_state'),
    ('fld_TSV040', 'MODEL_03_TARGET_MARKET_BETA_CORRELATION_VALUE', '3_target_market_beta_correlation'),
    ('fld_TSV047', 'MODEL_03_TARGET_NOISE_SCORE_BY_WINDOW_VALUE', '3_target_noise_score_<window>'),
    ('fld_TSV046', 'MODEL_03_TARGET_PATH_STABILITY_SCORE_BY_WINDOW_VALUE', '3_target_path_stability_score_<window>'),
    ('fld_TSV041', 'MODEL_03_TARGET_SECTOR_BETA_CORRELATION_VALUE', '3_target_sector_beta_correlation'),
    ('fld_TSV036', 'MODEL_03_TARGET_SESSION_POSITION_STATE_VALUE', '3_target_session_position_state'),
    ('trm_TSVWP001', 'MODEL_03_TARGET_SESSION_WINDOW_POLICY_COMPLETED_1MIN_BARS_VALUE', '3_target_session_window_policy_completed_1min_bars'),
    ('fld_TSV057', 'MODEL_03_TARGET_STATE_EMBEDDING_VALUE', '3_target_state_embedding'),
    ('fld_TSV054', 'MODEL_03_TARGET_STATE_EVIDENCE_COUNT_VALUE', '3_evidence_count'),
    ('fld_TSV009', 'MODEL_03_TARGET_STATE_FEATURES_VALUE', '3_target_state_features'),
    ('fld_TSV053', 'MODEL_03_TARGET_STATE_QUALITY_SCORE_VALUE', '3_state_quality_score'),
    ('fld_TSV056', 'MODEL_03_TARGET_STATE_SCORE_PAYLOAD_VALUE', '3_score_payload'),
    ('fld_TSV052', 'MODEL_03_TARGET_STATE_TRADABILITY_SCORE_BY_WINDOW_VALUE', '3_tradability_score_<window>'),
    ('fld_TSV055', 'MODEL_03_TARGET_STATE_VECTOR_PAYLOAD_VALUE', '3_target_state_vector'),
    ('trm_TSVWIN002', 'MODEL_03_TARGET_STATE_WINDOW_15MIN_VALUE', '3_state_window_15min'),
    ('trm_TSVWIN004', 'MODEL_03_TARGET_STATE_WINDOW_390MIN_VALUE', '3_state_window_390min'),
    ('trm_TSVWIN001', 'MODEL_03_TARGET_STATE_WINDOW_5MIN_VALUE', '3_state_window_5min'),
    ('trm_TSVWIN003', 'MODEL_03_TARGET_STATE_WINDOW_60MIN_VALUE', '3_state_window_60min'),
    ('fld_TSV048', 'MODEL_03_TARGET_TRANSITION_RISK_SCORE_BY_WINDOW_VALUE', '3_target_transition_risk_score_<window>'),
    ('fld_TSV045', 'MODEL_03_TARGET_TREND_QUALITY_SCORE_BY_WINDOW_VALUE', '3_target_trend_quality_score_<window>'),
    ('fld_TSV018', 'MODEL_03_TARGET_TREND_QUALITY_STATE_VALUE', '3_target_trend_quality_state'),
    ('fld_TSV032', 'MODEL_03_TARGET_VOLATILITY_RANGE_STATE_VALUE', '3_target_volatility_range_state'),
    ('fld_TSV034', 'MODEL_03_TARGET_VOLUME_ACTIVITY_STATE_VALUE', '3_target_volume_activity_state'),
    ('fld_TSV020', 'MODEL_03_TARGET_VS_MARKET_RESIDUAL_DIRECTION_VALUE', '3_target_vs_market_residual_direction'),
    ('fld_TSV038', 'MODEL_03_TARGET_VS_MARKET_VOLATILITY_VALUE', '3_target_vs_market_volatility'),
    ('fld_TSV021', 'MODEL_03_TARGET_VS_SECTOR_RESIDUAL_DIRECTION_VALUE', '3_target_vs_sector_residual_direction'),
    ('fld_TSV039', 'MODEL_03_TARGET_VS_SECTOR_VOLATILITY_VALUE', '3_target_vs_sector_volatility'),
    ('fld_TSV035', 'MODEL_03_TARGET_VWAP_LOCATION_STATE_VALUE', '3_target_vwap_location_state')
)
UPDATE trading_registry r
SET key = value_updates.new_key,
    payload = value_updates.new_payload,
    updated_at = CURRENT_TIMESTAMP
FROM value_updates
WHERE r.id = value_updates.id
  AND r.kind = 'state_vector_value'
  AND (r.key IS DISTINCT FROM value_updates.new_key
       OR r.payload IS DISTINCT FROM value_updates.new_payload);
