-- Register accepted Layer 4 EventOverlayModel event-context vector score families.
-- These are reviewed core event-context state_vector_value tokens, not source table
-- columns, event-artifact fields, alpha confidence, trading signal, expression, or
-- final-action outputs.

INSERT INTO trading_registry (id, kind, key, payload_format, payload, path, applies_to, artifact_sync_policy, note)
VALUES
  ('cfg_ECVH001', 'config', 'EVENT_CONTEXT_VECTOR_HORIZONS', 'text', '5min;15min;60min;390min', 'trading-model/docs/05_layer_04_event_overlay.md', 'event_context_vector;event_overlay_model;model_04_event_overlay', 'registry_only', 'Accepted EventOverlayModel V1 event-context horizons. Horizons are context-observation horizons, not trade-action variants.'),
  ('cfg_ECVS001', 'config', 'EVENT_CONTEXT_VECTOR_SCORE_FAMILIES', 'text', '4_event_presence_score_<horizon>;4_event_timing_proximity_score_<horizon>;4_event_intensity_score_<horizon>;4_event_direction_bias_score_<horizon>;4_event_context_alignment_score_<horizon>;4_event_uncertainty_score_<horizon>;4_event_gap_risk_score_<horizon>;4_event_reversal_risk_score_<horizon>;4_event_liquidity_disruption_score_<horizon>;4_event_contagion_risk_score_<horizon>;4_event_context_quality_score_<horizon>;4_event_market_impact_score_<horizon>;4_event_sector_impact_score_<horizon>;4_event_industry_impact_score_<horizon>;4_event_theme_factor_impact_score_<horizon>;4_event_peer_group_impact_score_<horizon>;4_event_symbol_impact_score_<horizon>;4_event_microstructure_impact_score_<horizon>;4_event_scope_confidence_score_<horizon>;4_event_scope_escalation_risk_score_<horizon>;4_event_target_relevance_score_<horizon>;4_event_dominant_impact_scope_<horizon>', 'trading-model/docs/05_layer_04_event_overlay.md', 'event_context_vector;event_overlay_model;model_04_event_overlay;state_vector_value', 'registry_only', 'Accepted Layer 4 EventOverlayModel V1 event-context score-family tokens. These families separate event presence, timing, intensity, direction bias, alignment, risks, quality, impact scope, scope confidence, escalation risk, target relevance, and dominant impact scope.'),
  ('fld_EOMV1001', 'state_vector_value', 'EVENT_PRESENCE_SCORE_BY_HORIZON', 'field_name', '4_event_presence_score_<horizon>', 'trading-model/docs/05_layer_04_event_overlay.md', 'event_context_vector;model_04_event_overlay;event_overlay_model;model_evaluation;promotion_evidence', 'registry_only', 'Layer 4 EventOverlay score family for relevant event presence by horizon; presence is not good/bad by itself.'),
  ('fld_EOMV1002', 'state_vector_value', 'EVENT_TIMING_PROXIMITY_SCORE_BY_HORIZON', 'field_name', '4_event_timing_proximity_score_<horizon>', 'trading-model/docs/05_layer_04_event_overlay.md', 'event_context_vector;model_04_event_overlay;event_overlay_model;model_evaluation;promotion_evidence', 'registry_only', 'Layer 4 EventOverlay score family for proximity to a sensitive event window by horizon.'),
  ('fld_EOMV1003', 'state_vector_value', 'EVENT_INTENSITY_SCORE_BY_HORIZON', 'field_name', '4_event_intensity_score_<horizon>', 'trading-model/docs/05_layer_04_event_overlay.md', 'event_context_vector;model_04_event_overlay;event_overlay_model;model_evaluation;promotion_evidence', 'registry_only', 'Layer 4 EventOverlay score family for event information-shock or attention intensity by horizon.'),
  ('fld_EOMV1004', 'state_vector_value', 'EVENT_DIRECTION_BIAS_SCORE_BY_HORIZON', 'field_name', '4_event_direction_bias_score_<horizon>', 'trading-model/docs/05_layer_04_event_overlay.md', 'event_context_vector;model_04_event_overlay;event_overlay_model;model_evaluation;promotion_evidence', 'registry_only', 'Layer 4 EventOverlay score family for signed target-conditioned event direction bias by horizon; this is not alpha confidence.'),
  ('fld_EOMV1005', 'state_vector_value', 'EVENT_CONTEXT_ALIGNMENT_SCORE_BY_HORIZON', 'field_name', '4_event_context_alignment_score_<horizon>', 'trading-model/docs/05_layer_04_event_overlay.md', 'event_context_vector;model_04_event_overlay;event_overlay_model;target_context_state;model_evaluation;promotion_evidence', 'registry_only', 'Layer 4 EventOverlay score family for whether event evidence supports or conflicts with current target_context_state by horizon.'),
  ('fld_EOMV1006', 'state_vector_value', 'EVENT_UNCERTAINTY_SCORE_BY_HORIZON', 'field_name', '4_event_uncertainty_score_<horizon>', 'trading-model/docs/05_layer_04_event_overlay.md', 'event_context_vector;model_04_event_overlay;event_overlay_model;model_evaluation;promotion_evidence', 'registry_only', 'Layer 4 EventOverlay high-is-bad score family for event-driven information uncertainty by horizon.'),
  ('fld_EOMV1007', 'state_vector_value', 'EVENT_GAP_RISK_SCORE_BY_HORIZON', 'field_name', '4_event_gap_risk_score_<horizon>', 'trading-model/docs/05_layer_04_event_overlay.md', 'event_context_vector;model_04_event_overlay;event_overlay_model;model_evaluation;promotion_evidence', 'registry_only', 'Layer 4 EventOverlay high-is-bad score family for event-driven gap or discrete jump risk by horizon.'),
  ('fld_EOMV1008', 'state_vector_value', 'EVENT_REVERSAL_RISK_SCORE_BY_HORIZON', 'field_name', '4_event_reversal_risk_score_<horizon>', 'trading-model/docs/05_layer_04_event_overlay.md', 'event_context_vector;model_04_event_overlay;event_overlay_model;target_context_state;model_evaluation;promotion_evidence', 'registry_only', 'Layer 4 EventOverlay high-is-bad score family for event-driven reversal risk against current target context by horizon.'),
  ('fld_EOMV1009', 'state_vector_value', 'EVENT_LIQUIDITY_DISRUPTION_SCORE_BY_HORIZON', 'field_name', '4_event_liquidity_disruption_score_<horizon>', 'trading-model/docs/05_layer_04_event_overlay.md', 'event_context_vector;model_04_event_overlay;event_overlay_model;model_evaluation;promotion_evidence', 'registry_only', 'Layer 4 EventOverlay high-is-bad score family for event-driven spread, depth, slippage, or liquidity-disruption risk by horizon.'),
  ('fld_EOMV1010', 'state_vector_value', 'EVENT_CONTAGION_RISK_SCORE_BY_HORIZON', 'field_name', '4_event_contagion_risk_score_<horizon>', 'trading-model/docs/05_layer_04_event_overlay.md', 'event_context_vector;model_04_event_overlay;event_overlay_model;model_evaluation;promotion_evidence', 'registry_only', 'Layer 4 EventOverlay high-is-bad score family for cross-scope event transmission or contagion risk by horizon.'),
  ('fld_EOMV1011', 'state_vector_value', 'EVENT_CONTEXT_QUALITY_SCORE_BY_HORIZON', 'field_name', '4_event_context_quality_score_<horizon>', 'trading-model/docs/05_layer_04_event_overlay.md', 'event_context_vector;model_04_event_overlay;event_overlay_model;model_evaluation;promotion_evidence', 'registry_only', 'Layer 4 EventOverlay high-is-good score family for event evidence quality by horizon.'),
  ('fld_EOMV1012', 'state_vector_value', 'EVENT_MARKET_IMPACT_SCORE_BY_HORIZON', 'field_name', '4_event_market_impact_score_<horizon>', 'trading-model/docs/05_layer_04_event_overlay.md', 'event_context_vector;model_04_event_overlay;event_overlay_model;market_context_state;model_evaluation;promotion_evidence', 'registry_only', 'Layer 4 EventOverlay score family for broad-market impact strength by horizon.'),
  ('fld_EOMV1013', 'state_vector_value', 'EVENT_SECTOR_IMPACT_SCORE_BY_HORIZON', 'field_name', '4_event_sector_impact_score_<horizon>', 'trading-model/docs/05_layer_04_event_overlay.md', 'event_context_vector;model_04_event_overlay;event_overlay_model;sector_context_state;model_evaluation;promotion_evidence', 'registry_only', 'Layer 4 EventOverlay score family for sector impact strength by horizon.'),
  ('fld_EOMV1014', 'state_vector_value', 'EVENT_INDUSTRY_IMPACT_SCORE_BY_HORIZON', 'field_name', '4_event_industry_impact_score_<horizon>', 'trading-model/docs/05_layer_04_event_overlay.md', 'event_context_vector;model_04_event_overlay;event_overlay_model;model_evaluation;promotion_evidence', 'registry_only', 'Layer 4 EventOverlay score family for industry impact strength by horizon.'),
  ('fld_EOMV1015', 'state_vector_value', 'EVENT_THEME_FACTOR_IMPACT_SCORE_BY_HORIZON', 'field_name', '4_event_theme_factor_impact_score_<horizon>', 'trading-model/docs/05_layer_04_event_overlay.md', 'event_context_vector;model_04_event_overlay;event_overlay_model;model_evaluation;promotion_evidence', 'registry_only', 'Layer 4 EventOverlay score family for cross-industry theme/factor impact strength by horizon.'),
  ('fld_EOMV1016', 'state_vector_value', 'EVENT_PEER_GROUP_IMPACT_SCORE_BY_HORIZON', 'field_name', '4_event_peer_group_impact_score_<horizon>', 'trading-model/docs/05_layer_04_event_overlay.md', 'event_context_vector;model_04_event_overlay;event_overlay_model;model_evaluation;promotion_evidence', 'registry_only', 'Layer 4 EventOverlay score family for peer-group impact strength by horizon.'),
  ('fld_EOMV1017', 'state_vector_value', 'EVENT_SYMBOL_IMPACT_SCORE_BY_HORIZON', 'field_name', '4_event_symbol_impact_score_<horizon>', 'trading-model/docs/05_layer_04_event_overlay.md', 'event_context_vector;model_04_event_overlay;event_overlay_model;model_evaluation;promotion_evidence', 'registry_only', 'Layer 4 EventOverlay score family for target/symbol-scope impact strength by horizon; raw ticker identity remains outside fitting vectors.'),
  ('fld_EOMV1018', 'state_vector_value', 'EVENT_MICROSTRUCTURE_IMPACT_SCORE_BY_HORIZON', 'field_name', '4_event_microstructure_impact_score_<horizon>', 'trading-model/docs/05_layer_04_event_overlay.md', 'event_context_vector;model_04_event_overlay;event_overlay_model;model_evaluation;promotion_evidence', 'registry_only', 'Layer 4 EventOverlay score family for spread, depth, halt, borrow, option-liquidity, IV, or order-flow microstructure impact by horizon.'),
  ('fld_EOMV1019', 'state_vector_value', 'EVENT_SCOPE_CONFIDENCE_SCORE_BY_HORIZON', 'field_name', '4_event_scope_confidence_score_<horizon>', 'trading-model/docs/05_layer_04_event_overlay.md', 'event_context_vector;model_04_event_overlay;event_overlay_model;model_evaluation;promotion_evidence', 'registry_only', 'Layer 4 EventOverlay score family for confidence in event impact-scope classification by horizon.'),
  ('fld_EOMV1020', 'state_vector_value', 'EVENT_SCOPE_ESCALATION_RISK_SCORE_BY_HORIZON', 'field_name', '4_event_scope_escalation_risk_score_<horizon>', 'trading-model/docs/05_layer_04_event_overlay.md', 'event_context_vector;model_04_event_overlay;event_overlay_model;model_evaluation;promotion_evidence', 'registry_only', 'Layer 4 EventOverlay high-is-bad score family for lower-scope event escalation into higher-scope impact by horizon.'),
  ('fld_EOMV1021', 'state_vector_value', 'EVENT_TARGET_RELEVANCE_SCORE_BY_HORIZON', 'field_name', '4_event_target_relevance_score_<horizon>', 'trading-model/docs/05_layer_04_event_overlay.md', 'event_context_vector;model_04_event_overlay;event_overlay_model;target_context_state;model_evaluation;promotion_evidence', 'registry_only', 'Layer 4 EventOverlay score family for event relevance to the current anonymous target candidate by horizon.'),
  ('fld_EOMV1022', 'state_vector_value', 'EVENT_DOMINANT_IMPACT_SCOPE_BY_HORIZON', 'field_name', '4_event_dominant_impact_scope_<horizon>', 'trading-model/docs/05_layer_04_event_overlay.md', 'event_context_vector;model_04_event_overlay;event_overlay_model;model_evaluation;promotion_evidence', 'registry_only', 'Layer 4 EventOverlay horizon-aware dominant impact-scope family for audit/debug/routing; numeric impact-scope score families remain preferred model evidence.')
ON CONFLICT (id) DO UPDATE SET
  kind = EXCLUDED.kind,
  key = EXCLUDED.key,
  payload_format = EXCLUDED.payload_format,
  payload = EXCLUDED.payload,
  path = EXCLUDED.path,
  applies_to = EXCLUDED.applies_to,
  artifact_sync_policy = EXCLUDED.artifact_sync_policy,
  note = EXCLUDED.note;
