-- Register stable local script entrypoints for Layers 4-8 and align source_06 semantics.
-- These wrappers provide generate/evaluate/review parity with Layers 1-3 while
-- remaining fixture/local-safe: production activation still requires reviewed
-- model-governance evidence and explicit approval.

INSERT INTO trading_registry (id, kind, key, payload_format, payload, path, applies_to, artifact_sync_policy, note)
VALUES
  ('scr_M4EOMGEN', 'script', 'MODEL_04_EVENT_OVERLAY_GENERATE', 'command', 'python3 scripts/models/model_04_event_overlay/generate_model_04_event_overlay.py', '/root/projects/trading-model/scripts/models/model_04_event_overlay/generate_model_04_event_overlay.py', 'trading-model;event_overlay_model;model_04_event_overlay;event_context_vector;source_04_event_overlay', 'sync_artifact', 'Stable callable entrypoint for generating deterministic Layer 4 EventOverlayModel event_context_vector rows from local/fixture event-overlay input evidence.'),
  ('scr_M4EOMEVAL', 'script', 'MODEL_04_EVENT_OVERLAY_EVALUATE_PROMOTION_EVIDENCE', 'command', 'python3 scripts/models/model_04_event_overlay/evaluate_model_04_event_overlay.py', '/root/projects/trading-model/scripts/models/model_04_event_overlay/evaluate_model_04_event_overlay.py', 'trading-model;event_overlay_model;model_04_event_overlay;event_context_vector;model_evaluation;promotion_evidence', 'sync_artifact', 'Stable callable entrypoint for building local/fixture EventOverlayModel evaluation labels and conservative promotion evidence summary. It does not write governance rows or activate configs.'),
  ('scr_M4EOMREV', 'script', 'MODEL_04_EVENT_OVERLAY_REVIEW_PROMOTION', 'command', 'python3 scripts/models/model_04_event_overlay/review_event_overlay_promotion.py', '/root/projects/trading-model/scripts/models/model_04_event_overlay/review_event_overlay_promotion.py', 'trading-model;event_overlay_model;model_04_event_overlay;model_evaluation;promotion_review', 'sync_artifact', 'Stable callable conservative promotion-review wrapper for EventOverlayModel. Fixture/local evidence must defer until real-data thresholds, baseline improvement, split stability, and leakage gates are reviewed and accepted.'),
  ('scr_M5ACGEN', 'script', 'MODEL_05_ALPHA_CONFIDENCE_GENERATE', 'command', 'python3 scripts/models/model_05_alpha_confidence/generate_model_05_alpha_confidence.py', '/root/projects/trading-model/scripts/models/model_05_alpha_confidence/generate_model_05_alpha_confidence.py', 'trading-model;alpha_confidence_model;model_05_alpha_confidence;alpha_confidence_vector;target_context_state;event_context_vector', 'sync_artifact', 'Stable callable entrypoint for generating deterministic Layer 5 AlphaConfidenceModel alpha_confidence_vector rows from local/fixture target and event context evidence.'),
  ('scr_M5ACEVAL', 'script', 'MODEL_05_ALPHA_CONFIDENCE_EVALUATE_PROMOTION_EVIDENCE', 'command', 'python3 scripts/models/model_05_alpha_confidence/evaluate_model_05_alpha_confidence.py', '/root/projects/trading-model/scripts/models/model_05_alpha_confidence/evaluate_model_05_alpha_confidence.py', 'trading-model;alpha_confidence_model;model_05_alpha_confidence;alpha_confidence_vector;model_evaluation;promotion_evidence', 'sync_artifact', 'Stable callable entrypoint for building local/fixture AlphaConfidenceModel evaluation labels and conservative promotion evidence summary. It does not write governance rows or activate configs.'),
  ('scr_M5ACREV', 'script', 'MODEL_05_ALPHA_CONFIDENCE_REVIEW_PROMOTION', 'command', 'python3 scripts/models/model_05_alpha_confidence/review_alpha_confidence_promotion.py', '/root/projects/trading-model/scripts/models/model_05_alpha_confidence/review_alpha_confidence_promotion.py', 'trading-model;alpha_confidence_model;model_05_alpha_confidence;model_evaluation;promotion_review', 'sync_artifact', 'Stable callable conservative promotion-review wrapper for AlphaConfidenceModel. Fixture/local evidence must defer until real-data thresholds, baseline improvement, split stability, and leakage gates are reviewed and accepted.'),
  ('scr_M6PPGEN', 'script', 'MODEL_06_POSITION_PROJECTION_GENERATE', 'command', 'python3 scripts/models/model_06_position_projection/generate_model_06_position_projection.py', '/root/projects/trading-model/scripts/models/model_06_position_projection/generate_model_06_position_projection.py', 'trading-model;position_projection_model;model_06_position_projection;position_projection_vector;alpha_confidence_vector', 'sync_artifact', 'Stable callable entrypoint for generating deterministic Layer 6 PositionProjectionModel position_projection_vector rows from local/fixture alpha, position, cost, and risk-budget evidence.'),
  ('scr_M6PPEVAL', 'script', 'MODEL_06_POSITION_PROJECTION_EVALUATE_PROMOTION_EVIDENCE', 'command', 'python3 scripts/models/model_06_position_projection/evaluate_model_06_position_projection.py', '/root/projects/trading-model/scripts/models/model_06_position_projection/evaluate_model_06_position_projection.py', 'trading-model;position_projection_model;model_06_position_projection;position_projection_vector;model_evaluation;promotion_evidence', 'sync_artifact', 'Stable callable entrypoint for building local/fixture PositionProjectionModel evaluation labels and conservative promotion evidence summary. It does not write governance rows or activate configs.'),
  ('scr_M6PPREV', 'script', 'MODEL_06_POSITION_PROJECTION_REVIEW_PROMOTION', 'command', 'python3 scripts/models/model_06_position_projection/review_position_projection_promotion.py', '/root/projects/trading-model/scripts/models/model_06_position_projection/review_position_projection_promotion.py', 'trading-model;position_projection_model;model_06_position_projection;model_evaluation;promotion_review', 'sync_artifact', 'Stable callable conservative promotion-review wrapper for PositionProjectionModel. Fixture/local evidence must defer until real-data thresholds, baseline improvement, split stability, and leakage gates are reviewed and accepted.'),
  ('scr_M7UAGEN', 'script', 'MODEL_07_UNDERLYING_ACTION_GENERATE', 'command', 'python3 scripts/models/model_07_underlying_action/generate_model_07_underlying_action.py', '/root/projects/trading-model/scripts/models/model_07_underlying_action/generate_model_07_underlying_action.py', 'trading-model;underlying_action_model;model_07_underlying_action;underlying_action_plan;position_projection_vector', 'sync_artifact', 'Stable callable entrypoint for generating deterministic Layer 7 UnderlyingActionModel underlying_action_plan rows from local/fixture projection, position, quote, liquidity, risk, and policy evidence.'),
  ('scr_M7UAEVAL', 'script', 'MODEL_07_UNDERLYING_ACTION_EVALUATE_PROMOTION_EVIDENCE', 'command', 'python3 scripts/models/model_07_underlying_action/evaluate_model_07_underlying_action.py', '/root/projects/trading-model/scripts/models/model_07_underlying_action/evaluate_model_07_underlying_action.py', 'trading-model;underlying_action_model;model_07_underlying_action;underlying_action_plan;model_evaluation;promotion_evidence', 'sync_artifact', 'Stable callable entrypoint for building local/fixture UnderlyingActionModel plan-quality labels and conservative promotion evidence summary. It does not write governance rows or activate configs.'),
  ('scr_M7UAREV', 'script', 'MODEL_07_UNDERLYING_ACTION_REVIEW_PROMOTION', 'command', 'python3 scripts/models/model_07_underlying_action/review_underlying_action_promotion.py', '/root/projects/trading-model/scripts/models/model_07_underlying_action/review_underlying_action_promotion.py', 'trading-model;underlying_action_model;model_07_underlying_action;model_evaluation;promotion_review', 'sync_artifact', 'Stable callable conservative promotion-review wrapper for UnderlyingActionModel. Fixture/local evidence must defer until real-data thresholds, baseline improvement, split stability, and leakage gates are reviewed and accepted.'),
  ('scr_M8OEGEN', 'script', 'MODEL_08_OPTION_EXPRESSION_GENERATE', 'command', 'python3 scripts/models/model_08_option_expression/generate_model_08_option_expression.py', '/root/projects/trading-model/scripts/models/model_08_option_expression/generate_model_08_option_expression.py', 'trading-model;option_expression_model;model_08_option_expression;option_expression_plan;underlying_action_plan;source_05_option_expression', 'sync_artifact', 'Stable callable entrypoint for generating deterministic Layer 8 OptionExpressionModel option_expression_plan rows from local/fixture action-plan, option-chain, quote, and policy evidence.'),
  ('scr_M8OEEVAL', 'script', 'MODEL_08_OPTION_EXPRESSION_EVALUATE_PROMOTION_EVIDENCE', 'command', 'python3 scripts/models/model_08_option_expression/evaluate_model_08_option_expression.py', '/root/projects/trading-model/scripts/models/model_08_option_expression/evaluate_model_08_option_expression.py', 'trading-model;option_expression_model;model_08_option_expression;option_expression_plan;model_evaluation;promotion_evidence', 'sync_artifact', 'Stable callable entrypoint for building local/fixture OptionExpressionModel evaluation labels and conservative promotion evidence summary. It does not write governance rows or activate configs.'),
  ('scr_M8OEREV', 'script', 'MODEL_08_OPTION_EXPRESSION_REVIEW_PROMOTION', 'command', 'python3 scripts/models/model_08_option_expression/review_option_expression_promotion.py', '/root/projects/trading-model/scripts/models/model_08_option_expression/review_option_expression_promotion.py', 'trading-model;option_expression_model;model_08_option_expression;model_evaluation;promotion_review', 'sync_artifact', 'Stable callable conservative promotion-review wrapper for OptionExpressionModel. Fixture/local evidence must defer until real-data thresholds, baseline improvement, split stability, and leakage gates are reviewed and accepted.')
ON CONFLICT (id) DO UPDATE SET
  kind = EXCLUDED.kind,
  key = EXCLUDED.key,
  payload_format = EXCLUDED.payload_format,
  payload = EXCLUDED.payload,
  path = EXCLUDED.path,
  applies_to = EXCLUDED.applies_to,
  artifact_sync_policy = EXCLUDED.artifact_sync_policy,
  note = EXCLUDED.note,
  updated_at = NOW();

UPDATE trading_registry
SET applies_to = 'trading-data;trading-model;option_expression_model;model_08_option_expression;selected_contract_tracking_source',
    note = '06 control-plane-facing selected-contract option time-series source for OptionExpressionModel replay/evaluation; fetches selected-contract option market data from feeds and writes trading_data.source_06_position_execution without emitting execution instructions.',
    updated_at = NOW()
WHERE key = 'SOURCE_06_POSITION_EXECUTION';
