-- Refresh active registry notes after the 2026-05-15 conceptual layer reorder.
-- Physical table/script/score tokens remain legacy until dedicated migrations rename them.

WITH updates(id, note) AS (
  VALUES
    ('cfg_ACVTP001', 'Conceptual Layer 4 output-tier policy: base/unadjusted alpha from Layer 1/2/3 is diagnostic-only, while final adjusted alpha_confidence_vector is the default downstream output for PositionProjectionModel. The legacy physical package/score prefix remains model_05 / 5_* until a dedicated migration.'),
    ('cfg_ACVS001', 'Accepted legacy 5_* AlphaConfidenceModel scalar score-family tokens for conceptual Layer 4. These 9 families separate alpha direction, strength, expected residual return, confidence, reliability, path quality, reversal risk, drawdown risk, and alpha-level tradability.'),
    ('cfg_ECVS001', 'Accepted legacy 4_* event-context scalar score-family tokens for conceptual Layer 8 EventRiskGovernor. These families separate event presence, timing, intensity, direction bias, alignment, risks, quality, impact scope, scope confidence, escalation risk, and target relevance; enum-like audit fields remain model-local.'),
    ('cfg_L8OPT001', 'Legacy physical layer_08_option_expression contract bucket expansion scans listed expirations from near to far for the conceptual Layer 7 option-expression boundary.'),
    ('cfg_L8OPT004', 'Legacy physical layer_08_option_expression V1 option-expression coverage is single-leg only for the conceptual Layer 7 option-expression boundary: long call, long put, or no-option expression. Multi-leg spreads are deferred beyond V1.'),
    ('cfg_MWFP002', 'Formal workflow progression is segmented by dataset unit: Layers 1-2 use one six-month panel; Layers 3-7 run one selected target symbol over one six-month unit; the legacy physical option-expression bucket stage remains layer_08_option_expression until renamed; conceptual Layer 8 EventRiskGovernor is a separate event-risk overlay.'),
    ('cfg_OEPB001', 'Conceptual Layer 7 option-expression boundary policy: OptionExpressionModel produces an offline option-expression plan and expression vector. It must not place orders, emit broker order fields, choose route/time-in-force, emit final order quantity, mutate broker/account state, create maintain/no-trade overlays in V1, use 0DTE in V1, use adjusted contracts in V1, select contracts outside the preferred delta policy, or select strikes outside coherent underlying-action target-range guardrails.'),
    ('cfg_OEPT001', 'Accepted conceptual Layer 7 V1 option-expression type vocabulary. V1 supports single-leg long call, single-leg long put, and no-option-expression outcomes only.'),
    ('cfg_OEVS001', 'Accepted legacy 8_* OptionExpressionModel scalar score-family tokens for conceptual Layer 7. These 10 families separate option-expression eligibility, signed expression direction, contract fit, liquidity fit, IV fit, Greek fit, reward/risk, theta risk, fill quality, and expression confidence.'),
    ('cfg_PAE001', 'Canonical price-action event tokens for conceptual Layer 8 EventRiskGovernor. They describe board/tape behavior used as event-risk evidence, not buy/sell/hold decisions or execution instructions.'),
    ('cfg_PPVBP001', 'Conceptual Layer 5 boundary policy: target exposure is abstract risk exposure, position gap is not an execution instruction, and PositionProjectionModel does not emit buy/sell/hold/open/close/reverse, choose instruments, read option chains, or mutate broker/account state. Conceptual Layer 6 owns planned direct-underlying action; conceptual Layer 7 owns option expression.'),
    ('cfg_PPVHS001', 'Reviewed legacy 6_* handoff summary field-family tokens for communicating resolved target holding state from conceptual Layer 5 PositionProjectionModel to conceptual Layer 6 UnderlyingActionModel. These are not buy/sell/hold, planned quantities, order instructions, or option-expression fields.'),
    ('cfg_PPVS001', 'Accepted legacy 6_* PositionProjectionModel scalar score-family tokens for conceptual Layer 5 target holding-state projection. These 10 families separate target bias, target exposure, current-position alignment, position gap, utility, cost pressure, risk fit, stability, and projection confidence.'),
    ('cfg_UAPB001', 'Conceptual Layer 6 boundary policy: UnderlyingActionModel produces an offline direct stock/ETF action thesis and conceptual Layer 7 trading-guidance handoff. It must not place orders, emit broker order fields, choose option contracts, or mutate broker/account state.'),
    ('cfg_UAVS001', 'Accepted legacy 7_* UnderlyingActionModel scalar score-family tokens for conceptual Layer 6. These 10 families separate trade eligibility, signed action direction, action intensity, entry quality, expected return, adverse risk, reward/risk, liquidity fit, holding-time fit, and action confidence.'),
    ('dki_EOFS001', 'Legacy physical feature_04_event_overlay feature surface for conceptual Layer 8 EventRiskGovernor. trading-data derives point-in-time event-category, scope, dedup, source-priority, and quality payloads from accepted source_04_event_overlay rows; trading-model owns final event-risk context/intervention construction.'),
    ('dki_OEFS001', 'Legacy physical feature_08_option_expression option-expression candidate feature surface for conceptual Layer 7. trading-data derives point-in-time moneyness, spread/liquidity, IV, Greeks, and quality payloads from accepted source_05_option_expression rows; trading-model owns contract ranking and expression choice.'),
    ('scr_M5ACGEN', 'Stable callable entrypoint for generating deterministic conceptual Layer 4 AlphaConfidenceModel alpha_confidence_vector rows. The physical package remains model_05_alpha_confidence until a dedicated migration.'),
    ('scr_M6PPGEN', 'Stable callable entrypoint for generating deterministic conceptual Layer 5 PositionProjectionModel position_projection_vector rows. The physical package remains model_06_position_projection until a dedicated migration.'),
    ('scr_M7UAGEN', 'Stable callable entrypoint for generating deterministic conceptual Layer 6 UnderlyingActionModel underlying_action_plan rows. The physical package remains model_07_underlying_action until a dedicated migration.'),
    ('scr_M8ERGGEN', 'Stable callable entrypoint for generating deterministic conceptual Layer 8 EventRiskGovernor event-risk context/intervention rows from local/fixture event-risk input evidence.'),
    ('scr_M8OEGEN', 'Stable callable entrypoint for generating deterministic conceptual Layer 7 OptionExpressionModel option_expression_plan rows. The physical package remains model_08_option_expression until a dedicated migration.'),
    ('trm_ACM001', 'Accepted canonical conceptual Layer 4 model id. AlphaConfidenceModel builds base/unadjusted alpha diagnostics from the Layer 1/2/3 state stack and emits alpha_confidence_vector; it is separate from Layer 3 state evidence, Layer 8 event-risk governance, and Layer 5 position projection.'),
    ('trm_ASV001', 'Conceptual Layer 4 AlphaConfidenceModel final adjusted output vector with horizon-aware alpha direction, strength, expected residual return, confidence, reliability, path quality, reversal risk, drawdown risk, and alpha-level tradability; not a final action, target exposure, position-sizing, or option-expression instruction.'),
    ('trm_EGFM001', 'Event-risk source category for earnings/guidance overview rows. Calendar rows are scheduled shells only; official SEC/company artifacts are result/guidance evidence.'),
    ('trm_ECV001', 'Conceptual Layer 8 point-in-time event-context / event-risk-governor evidence output. It contains event timing, scope, type, intensity, directional context, risk context, and quality context without action or execution instructions; it is not a hard upstream alpha prerequisite.'),
    ('trm_EXV001', 'Conceptual Layer 7 scalar/vector output for option-expression quality by horizon. It carries eligibility, signed expression direction, contract fit, liquidity fit, IV, Greek fit, reward/risk, theta risk, fill quality, and expression confidence; it is not an order instruction.'),
    ('term_DU001', 'Accepted dataset-unit policy: Layers 1-2 use one six-month panel; Layers 3-7 use one selected target symbol over one six-month window; the legacy physical option-expression expansion remains layer_08_option_expression until renamed, while conceptual Layer 8 EventRiskGovernor is a separate event-risk overlay.'),
    ('term_L8EVTCOV002', 'Conceptual Layer 8 event-risk write-mode materialization requires each required reviewed event-feed artifact family to contain at least one row in the requested [start_month, end_month_next) window. Artifact presence alone is not sufficient.'),
    ('term_L8EVTCOV001', 'Conceptual Layer 8 event-source coverage requires reviewed local artifacts with requested-window row coverage for Alpaca news, GDELT news, SEC company financials, and Trading Economics calendar rows before event-risk-dependent outputs may advance.'),
    ('trm_MAC001', 'Accepted legacy model_05_alpha_confidence model-output surface name for conceptual Layer 4 AlphaConfidenceModel final adjusted alpha_confidence_vector outputs. Base/unadjusted alpha fields are diagnostics, not the default downstream surface.'),
    ('trm_MTP001', 'Accepted legacy model_06_position_projection model-output surface name for conceptual Layer 5 PositionProjectionModel position_projection_vector outputs.'),
    ('trm_M7UAM01', 'Accepted legacy model_07_underlying_action model-output surface name for conceptual Layer 6 UnderlyingActionModel underlying_action_plan and underlying_action_vector outputs.'),
    ('trm_M7OEM01', 'Accepted legacy model_08_option_expression model-output surface name for conceptual Layer 7 OptionExpressionModel option_expression_plan and expression_vector outputs. This is not live execution.'),
    ('trm_OEM001', 'Accepted conceptual Layer 7 option-expression model id. OptionExpressionModel consumes underlying path assumptions plus point-in-time option-chain context and emits offline option_expression_plan / expression_vector rows; it does not place orders, route orders, or mutate broker/account state.'),
    ('trm_OEP001', 'Conceptual Layer 7 primary offline option-expression output. It includes selected expression type, selected option right, point-in-time selected contract reference, contract constraints, premium-risk plan, underlying thesis reference, reason codes, and diagnostics; it is not a broker order or account mutation.'),
    ('trm_POEC001', 'Conceptual Layer 7 point-in-time pending option exposure context used to avoid duplicate option-expression plans. It is not a new order instruction.'),
    ('trm_TPM001', 'Accepted canonical conceptual Layer 5 model id. PositionProjectionModel maps final adjusted alpha confidence plus current/pending position, position-level friction, portfolio exposure, and risk-budget context to projected target holding state; it is not buy/sell/hold, expression selection, or live execution.'),
    ('trm_TSVEC01', 'Conceptual Layer 5 PositionProjectionModel output vector for projected target holding state before conceptual Layer 6 direct-underlying action planning. It carries target exposure, position gap, utility, cost/risk fit, stability, and projection confidence; it is not an order instruction, planned action, option expression, or final action.'),
    ('trm_UAM001', 'Accepted canonical conceptual Layer 6 model id. UnderlyingActionModel maps alpha/position state plus point-in-time current/pending underlying exposure, quote/liquidity/borrow state, risk-budget state, and policy gates into an offline direct stock/ETF planned action thesis; it is not option expression or live execution.')
)
UPDATE trading_registry AS registry
SET note = updates.note,
    updated_at = NOW()
FROM updates
WHERE registry.id = updates.id;
