-- Remove remaining drift/version suffixes from active registry semantic names.

DO $$
DECLARE
    pair text[];
BEGIN
    FOREACH pair SLICE 1 IN ARRAY ARRAY[
        ARRAY['archive_receipt_draft_v1', 'archive_receipt_draft'],
        ARRAY['archive_receipt_v1', 'archive_receipt'],
        ARRAY['artifact_tombstone_draft_v1', 'artifact_tombstone_draft'],
        ARRAY['compression_manifest_draft_v1', 'compression_manifest_draft'],
        ARRAY['compression_manifest_v1', 'compression_manifest'],
        ARRAY['compression_receipt_draft_v1', 'compression_receipt_draft'],
        ARRAY['compression_receipt_v1', 'compression_receipt'],
        ARRAY['cpi_inflation_association_readiness_v1', 'cpi_inflation_association_readiness'],
        ARRAY['dashboard_snapshot_prune_plan_v1', 'dashboard_snapshot_prune_plan'],
        ARRAY['dashboard_snapshot_prune_receipt_v1', 'dashboard_snapshot_prune_receipt'],
        ARRAY['dashboard_snapshot_prune_summary_v1', 'dashboard_snapshot_prune_summary'],
        ARRAY['deletion_receipt_draft_v1', 'deletion_receipt_draft'],
        ARRAY['earnings_guidance_artifact_coverage_scout_v1', 'earnings_guidance_artifact_coverage_scout'],
        ARRAY['earnings_guidance_baseline_source_audit_v1', 'earnings_guidance_baseline_source_audit'],
        ARRAY['earnings_guidance_current_prior_comparison_readiness_v1', 'earnings_guidance_current_prior_comparison_readiness'],
        ARRAY['earnings_guidance_event_alone_scouting_study_v1', 'earnings_guidance_event_alone_scouting_study'],
        ARRAY['earnings_guidance_event_family_scouting_study_v1', 'earnings_guidance_event_family_scouting_study'],
        ARRAY['earnings_guidance_expectation_baseline_readiness_v1', 'earnings_guidance_expectation_baseline_readiness'],
        ARRAY['earnings_guidance_interpretation_review_v1', 'earnings_guidance_interpretation_review'],
        ARRAY['earnings_guidance_nasdaq_future_calendar_probe_v1', 'earnings_guidance_nasdaq_future_calendar_probe'],
        ARRAY['earnings_guidance_prior_guidance_exhibit_extraction_v1', 'earnings_guidance_prior_guidance_exhibit_extraction'],
        ARRAY['earnings_guidance_prior_guidance_extraction_v1', 'earnings_guidance_prior_guidance_extraction'],
        ARRAY['earnings_guidance_prior_official_baseline_source_audit_v1', 'earnings_guidance_prior_official_baseline_source_audit'],
        ARRAY['earnings_guidance_prior_official_document_coverage_v1', 'earnings_guidance_prior_official_document_coverage'],
        ARRAY['earnings_guidance_readiness_scout_v1', 'earnings_guidance_readiness_scout'],
        ARRAY['earnings_guidance_result_artifact_scout_v1', 'earnings_guidance_result_artifact_scout'],
        ARRAY['earnings_guidance_text_candidate_scout_v1', 'earnings_guidance_text_candidate_scout'],
        ARRAY['earnings_option_abnormality_split_scout_v1', 'earnings_option_abnormality_split_scout'],
        ARRAY['earnings_option_control_verification_v1', 'earnings_option_control_verification'],
        ARRAY['event_family_all_association_summary_v1', 'event_family_all_association_summary'],
        ARRAY['event_family_all_association_v1', 'event_family_all_association'],
        ARRAY['event_family_batch_catalog_v1', 'event_family_batch_catalog'],
        ARRAY['event_family_batch_summary_v1', 'event_family_batch_summary'],
        ARRAY['event_family_empirical_coverage_summary_v1', 'event_family_empirical_coverage_summary'],
        ARRAY['event_family_empirical_coverage_v1', 'event_family_empirical_coverage'],
        ARRAY['event_family_first_pass_packet_v1', 'event_family_first_pass_packet'],
        ARRAY['event_family_precondition_completion_summary_v1', 'event_family_precondition_completion_summary'],
        ARRAY['event_family_precondition_completion_v1', 'event_family_precondition_completion'],
        ARRAY['event_family_remaining_acceptance_summary_v1', 'event_family_remaining_acceptance_summary'],
        ARRAY['event_family_remaining_acceptance_v1', 'event_family_remaining_acceptance'],
        ARRAY['event_family_scouting_packet_v1', 'event_family_scouting_packet'],
        ARRAY['event_family_strategy_promotion_review_packet_v1', 'event_family_strategy_promotion_review_packet'],
        ARRAY['event_family_threshold_grading_summary_v1', 'event_family_threshold_grading_summary'],
        ARRAY['event_family_threshold_grading_v1', 'event_family_threshold_grading'],
        ARRAY['event_interpretation_v1', 'event_interpretation'],
        ARRAY['event_layer_final_judgment_summary_v1', 'event_layer_final_judgment_summary'],
        ARRAY['event_layer_final_judgment_v1', 'event_layer_final_judgment'],
        ARRAY['event_model_acceptance_report_v1', 'event_model_acceptance_report'],
        ARRAY['event_observation_pool_policy_summary_v1', 'event_observation_pool_policy_summary'],
        ARRAY['event_observation_pool_policy_v1', 'event_observation_pool_policy'],
        ARRAY['event_price_association_readiness_batch_v1', 'event_price_association_readiness_batch'],
        ARRAY['manager_event_model_regeneration_plan_v1', 'manager_event_model_regeneration_plan'],
        ARRAY['manager_historical_work_selection_v1', 'manager_historical_work_selection'],
        ARRAY['manager_scheduler_daemon_state_v1', 'manager_scheduler_daemon_state'],
        ARRAY['manager_scheduler_decision_v1', 'manager_scheduler_decision'],
        ARRAY['manager_source_existing_bootstrap_v1', 'manager_source_existing_bootstrap'],
        ARRAY['option_abnormality_non_earnings_saturation_v1', 'option_abnormality_non_earnings_saturation'],
        ARRAY['price_anomaly_event_discovery_summary_v1', 'price_anomaly_event_discovery_summary'],
        ARRAY['price_anomaly_event_discovery_v1', 'price_anomaly_event_discovery'],
        ARRAY['quarantine_receipt_draft_v1', 'quarantine_receipt_draft'],
        ARRAY['residual_anomaly_event_discovery_summary_v1', 'residual_anomaly_event_discovery_summary'],
        ARRAY['residual_anomaly_event_discovery_v1', 'residual_anomaly_event_discovery'],
        ARRAY['restore_receipt_draft_v1', 'restore_receipt_draft'],
        ARRAY['restore_receipt_v1', 'restore_receipt'],
        ARRAY['same_symbol_non_earnings_option_control_verification_v1', 'same_symbol_non_earnings_option_control_verification'],
        ARRAY['sql_archive_manifest_draft_v1', 'sql_archive_manifest_draft'],
        ARRAY['sql_archive_manifest_v1', 'sql_archive_manifest'],
        ARRAY['storage_artifact_index_summary_v1', 'storage_artifact_index_summary'],
        ARRAY['storage_artifact_index_v1', 'storage_artifact_index'],
        ARRAY['storage_file_lifecycle_acceptance_summary_v1', 'storage_file_lifecycle_acceptance_summary'],
        ARRAY['storage_file_lifecycle_acceptance_v1', 'storage_file_lifecycle_acceptance'],
        ARRAY['storage_lifecycle_execution_scaffold_summary_v1', 'storage_lifecycle_execution_scaffold_summary'],
        ARRAY['storage_lifecycle_execution_scaffold_v1', 'storage_lifecycle_execution_scaffold'],
        ARRAY['storage_lifecycle_plan_summary_v1', 'storage_lifecycle_plan_summary'],
        ARRAY['storage_lifecycle_plan_v1', 'storage_lifecycle_plan'],
        ARRAY['storage_protected_set_summary_v1', 'storage_protected_set_summary'],
        ARRAY['storage_protected_set_v1', 'storage_protected_set'],
        ARRAY['storage_quarantine_delete_result_v1', 'storage_quarantine_delete_result'],
        ARRAY['storage_quarantine_delete_summary_v1', 'storage_quarantine_delete_summary'],
        ARRAY['storage_quarantine_recheck_evidence_v1', 'storage_quarantine_recheck_evidence'],
        ARRAY['storage_quarantine_recheck_summary_v1', 'storage_quarantine_recheck_summary'],
        ARRAY['storage_single_file_compression_result_v1', 'storage_single_file_compression_result'],
        ARRAY['storage_single_file_compression_summary_v1', 'storage_single_file_compression_summary'],
        ARRAY['storage_sql_archive_restore_verification_summary_v1', 'storage_sql_archive_restore_verification_summary'],
        ARRAY['storage_sql_archive_restore_verification_v1', 'storage_sql_archive_restore_verification'],
        ARRAY['storage_sql_archive_result_v1', 'storage_sql_archive_result'],
        ARRAY['storage_sql_archive_summary_v1', 'storage_sql_archive_summary'],
        ARRAY['target_layer2_context_mapping_v1', 'target_layer2_context_mapping'],
        ARRAY['TARGET_LAYER2_CONTEXT_MAPPING_V1', 'TARGET_LAYER2_CONTEXT_MAPPING']
    ] LOOP
        UPDATE trading_registry
        SET key = replace(key, pair[1], pair[2]),
            payload = replace(payload, pair[1], pair[2]),
            path = replace(path, pair[1], pair[2]),
            applies_to = replace(applies_to, pair[1], pair[2]),
            note = replace(note, pair[1], pair[2]),
            updated_at = NOW()
        WHERE key LIKE '%' || pair[1] || '%'
           OR payload LIKE '%' || pair[1] || '%'
           OR path LIKE '%' || pair[1] || '%'
           OR applies_to LIKE '%' || pair[1] || '%'
           OR note LIKE '%' || pair[1] || '%';
    END LOOP;
END $$;
